// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type {
  GetAbilitiesData,
  GetAbilitiesErrors,
  GetAbilitiesForeignKeysByClassesData,
  GetAbilitiesForeignKeysByClassesErrors,
  GetAbilitiesForeignKeysByClassesResponses,
  GetAbilitiesForeignKeysByHeroesData,
  GetAbilitiesForeignKeysByHeroesErrors,
  GetAbilitiesForeignKeysByHeroesResponses,
  GetAbilitiesForeignKeysByMonstersData,
  GetAbilitiesForeignKeysByMonstersErrors,
  GetAbilitiesForeignKeysByMonstersResponses,
  GetAbilitiesResponses,
  GetClassesData,
  GetClassesErrors,
  GetClassesForeignKeysByHeroesData,
  GetClassesForeignKeysByHeroesErrors,
  GetClassesForeignKeysByHeroesResponses,
  GetClassesResponses,
  GetDialogsData,
  GetDialogsErrors,
  GetDialogsResponses,
  GetEffectsData,
  GetEffectsErrors,
  GetEffectsForeignKeysByAbilitiesData,
  GetEffectsForeignKeysByAbilitiesErrors,
  GetEffectsForeignKeysByAbilitiesResponses,
  GetEffectsResponses,
  GetFactionsData,
  GetFactionsErrors,
  GetFactionsForeignKeysByMonstersData,
  GetFactionsForeignKeysByMonstersErrors,
  GetFactionsForeignKeysByMonstersResponses,
  GetFactionsForeignKeysByNpcsData,
  GetFactionsForeignKeysByNpcsErrors,
  GetFactionsForeignKeysByNpcsResponses,
  GetFactionsResponses,
  GetHeroesData,
  GetHeroesErrors,
  GetHeroesForeignKeysByPartiesData,
  GetHeroesForeignKeysByPartiesErrors,
  GetHeroesForeignKeysByPartiesResponses,
  GetHeroesResponses,
  GetItemsData,
  GetItemsErrors,
  GetItemsForeignKeysByHeroesData,
  GetItemsForeignKeysByHeroesErrors,
  GetItemsForeignKeysByHeroesResponses,
  GetItemsForeignKeysByMonstersData,
  GetItemsForeignKeysByMonstersErrors,
  GetItemsForeignKeysByMonstersResponses,
  GetItemsForeignKeysByNpcsData,
  GetItemsForeignKeysByNpcsErrors,
  GetItemsForeignKeysByNpcsResponses,
  GetItemsForeignKeysByQuestsData,
  GetItemsForeignKeysByQuestsErrors,
  GetItemsForeignKeysByQuestsResponses,
  GetItemsResponses,
  GetItemTypesData,
  GetItemTypesErrors,
  GetItemTypesForeignKeysByItemsData,
  GetItemTypesForeignKeysByItemsErrors,
  GetItemTypesForeignKeysByItemsResponses,
  GetItemTypesResponses,
  GetLocationsData,
  GetLocationsErrors,
  GetLocationsForeignKeysByNpcsData,
  GetLocationsForeignKeysByNpcsErrors,
  GetLocationsForeignKeysByNpcsResponses,
  GetLocationsForeignKeysByQuestsData,
  GetLocationsForeignKeysByQuestsErrors,
  GetLocationsForeignKeysByQuestsResponses,
  GetLocationsResponses,
  GetMonstersData,
  GetMonstersErrors,
  GetMonstersResponses,
  GetNpcsData,
  GetNpcsErrors,
  GetNpcsForeignKeysByDialogsData,
  GetNpcsForeignKeysByDialogsErrors,
  GetNpcsForeignKeysByDialogsResponses,
  GetNpcsForeignKeysByQuestsData,
  GetNpcsForeignKeysByQuestsErrors,
  GetNpcsForeignKeysByQuestsResponses,
  GetNpcsResponses,
  GetPartiesData,
  GetPartiesErrors,
  GetPartiesResponses,
  GetQuestsData,
  GetQuestsErrors,
  GetQuestsResponses,
  GetRegionsData,
  GetRegionsErrors,
  GetRegionsForeignKeysByLocationsData,
  GetRegionsForeignKeysByLocationsErrors,
  GetRegionsForeignKeysByLocationsResponses,
  GetRegionsResponses,
  GetStatsData,
  GetStatsErrors,
  GetStatsForeignKeysByItemsData,
  GetStatsForeignKeysByItemsErrors,
  GetStatsForeignKeysByItemsResponses,
  GetStatsResponses,
  ListAbilitiesData,
  ListAbilitiesErrors,
  ListAbilitiesResponses,
  ListClassesData,
  ListClassesErrors,
  ListClassesResponses,
  ListDialogsData,
  ListDialogsErrors,
  ListDialogsResponses,
  ListEffectsData,
  ListEffectsErrors,
  ListEffectsResponses,
  ListFactionsData,
  ListFactionsErrors,
  ListFactionsResponses,
  ListHeroesData,
  ListHeroesErrors,
  ListHeroesResponses,
  ListItemsData,
  ListItemsErrors,
  ListItemsResponses,
  ListItemTypesData,
  ListItemTypesErrors,
  ListItemTypesResponses,
  ListLocationsData,
  ListLocationsErrors,
  ListLocationsResponses,
  ListMonstersData,
  ListMonstersErrors,
  ListMonstersResponses,
  ListNpcsData,
  ListNpcsErrors,
  ListNpcsResponses,
  ListPartiesData,
  ListPartiesErrors,
  ListPartiesResponses,
  ListQuestsData,
  ListQuestsErrors,
  ListQuestsResponses,
  ListRegionsData,
  ListRegionsErrors,
  ListRegionsResponses,
  ListStatsData,
  ListStatsErrors,
  ListStatsResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Query abilities rows
 *
 * Returns a paginated list of abilities rows with filtering and sorting
 */
export const listAbilities = <ThrowOnError extends boolean = false>(
  options: Options<ListAbilitiesData, ThrowOnError>,
) =>
  (options.client ?? client).post<ListAbilitiesResponses, ListAbilitiesErrors, ThrowOnError>({
    security: [
      { scheme: 'bearer', type: 'http' },
      { name: 'X-Api-Key', type: 'apiKey' },
    ],
    url: '/tables/abilities/rows',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get abilities by ID
 *
 * Returns a single abilities row by its ID
 */
export const getAbilities = <ThrowOnError extends boolean = false>(
  options: Options<GetAbilitiesData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetAbilitiesResponses, GetAbilitiesErrors, ThrowOnError>({
    security: [
      { scheme: 'bearer', type: 'http' },
      { name: 'X-Api-Key', type: 'apiKey' },
    ],
    url: '/tables/abilities/row/{rowId}',
    ...options,
  });

/**
 * Get abilities foreign keys by classes
 *
 * Returns rows from classes that reference this abilities
 */
export const getAbilitiesForeignKeysByClasses = <ThrowOnError extends boolean = false>(
  options: Options<GetAbilitiesForeignKeysByClassesData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetAbilitiesForeignKeysByClassesResponses,
    GetAbilitiesForeignKeysByClassesErrors,
    ThrowOnError
  >({
    security: [
      { scheme: 'bearer', type: 'http' },
      { name: 'X-Api-Key', type: 'apiKey' },
    ],
    url: '/tables/abilities/row/{rowId}/foreign-keys-by/classes',
    ...options,
  });

/**
 * Get abilities foreign keys by heroes
 *
 * Returns rows from heroes that reference this abilities
 */
export const getAbilitiesForeignKeysByHeroes = <ThrowOnError extends boolean = false>(
  options: Options<GetAbilitiesForeignKeysByHeroesData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetAbilitiesForeignKeysByHeroesResponses,
    GetAbilitiesForeignKeysByHeroesErrors,
    ThrowOnError
  >({
    security: [
      { scheme: 'bearer', type: 'http' },
      { name: 'X-Api-Key', type: 'apiKey' },
    ],
    url: '/tables/abilities/row/{rowId}/foreign-keys-by/heroes',
    ...options,
  });

/**
 * Get abilities foreign keys by monsters
 *
 * Returns rows from monsters that reference this abilities
 */
export const getAbilitiesForeignKeysByMonsters = <ThrowOnError extends boolean = false>(
  options: Options<GetAbilitiesForeignKeysByMonstersData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetAbilitiesForeignKeysByMonstersResponses,
    GetAbilitiesForeignKeysByMonstersErrors,
    ThrowOnError
  >({
    security: [
      { scheme: 'bearer', type: 'http' },
      { name: 'X-Api-Key', type: 'apiKey' },
    ],
    url: '/tables/abilities/row/{rowId}/foreign-keys-by/monsters',
    ...options,
  });

/**
 * Query classes rows
 *
 * Returns a paginated list of classes rows with filtering and sorting
 */
export const listClasses = <ThrowOnError extends boolean = false>(
  options: Options<ListClassesData, ThrowOnError>,
) =>
  (options.client ?? client).post<ListClassesResponses, ListClassesErrors, ThrowOnError>({
    security: [
      { scheme: 'bearer', type: 'http' },
      { name: 'X-Api-Key', type: 'apiKey' },
    ],
    url: '/tables/classes/rows',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get classes by ID
 *
 * Returns a single classes row by its ID
 */
export const getClasses = <ThrowOnError extends boolean = false>(
  options: Options<GetClassesData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetClassesResponses, GetClassesErrors, ThrowOnError>({
    security: [
      { scheme: 'bearer', type: 'http' },
      { name: 'X-Api-Key', type: 'apiKey' },
    ],
    url: '/tables/classes/row/{rowId}',
    ...options,
  });

/**
 * Get classes foreign keys by heroes
 *
 * Returns rows from heroes that reference this classes
 */
export const getClassesForeignKeysByHeroes = <ThrowOnError extends boolean = false>(
  options: Options<GetClassesForeignKeysByHeroesData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetClassesForeignKeysByHeroesResponses,
    GetClassesForeignKeysByHeroesErrors,
    ThrowOnError
  >({
    security: [
      { scheme: 'bearer', type: 'http' },
      { name: 'X-Api-Key', type: 'apiKey' },
    ],
    url: '/tables/classes/row/{rowId}/foreign-keys-by/heroes',
    ...options,
  });

/**
 * Query dialogs rows
 *
 * Returns a paginated list of dialogs rows with filtering and sorting
 */
export const listDialogs = <ThrowOnError extends boolean = false>(
  options: Options<ListDialogsData, ThrowOnError>,
) =>
  (options.client ?? client).post<ListDialogsResponses, ListDialogsErrors, ThrowOnError>({
    security: [
      { scheme: 'bearer', type: 'http' },
      { name: 'X-Api-Key', type: 'apiKey' },
    ],
    url: '/tables/dialogs/rows',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get dialogs by ID
 *
 * Returns a single dialogs row by its ID
 */
export const getDialogs = <ThrowOnError extends boolean = false>(
  options: Options<GetDialogsData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetDialogsResponses, GetDialogsErrors, ThrowOnError>({
    security: [
      { scheme: 'bearer', type: 'http' },
      { name: 'X-Api-Key', type: 'apiKey' },
    ],
    url: '/tables/dialogs/row/{rowId}',
    ...options,
  });

/**
 * Query effects rows
 *
 * Returns a paginated list of effects rows with filtering and sorting
 */
export const listEffects = <ThrowOnError extends boolean = false>(
  options: Options<ListEffectsData, ThrowOnError>,
) =>
  (options.client ?? client).post<ListEffectsResponses, ListEffectsErrors, ThrowOnError>({
    security: [
      { scheme: 'bearer', type: 'http' },
      { name: 'X-Api-Key', type: 'apiKey' },
    ],
    url: '/tables/effects/rows',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get effects by ID
 *
 * Returns a single effects row by its ID
 */
export const getEffects = <ThrowOnError extends boolean = false>(
  options: Options<GetEffectsData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetEffectsResponses, GetEffectsErrors, ThrowOnError>({
    security: [
      { scheme: 'bearer', type: 'http' },
      { name: 'X-Api-Key', type: 'apiKey' },
    ],
    url: '/tables/effects/row/{rowId}',
    ...options,
  });

/**
 * Get effects foreign keys by abilities
 *
 * Returns rows from abilities that reference this effects
 */
export const getEffectsForeignKeysByAbilities = <ThrowOnError extends boolean = false>(
  options: Options<GetEffectsForeignKeysByAbilitiesData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetEffectsForeignKeysByAbilitiesResponses,
    GetEffectsForeignKeysByAbilitiesErrors,
    ThrowOnError
  >({
    security: [
      { scheme: 'bearer', type: 'http' },
      { name: 'X-Api-Key', type: 'apiKey' },
    ],
    url: '/tables/effects/row/{rowId}/foreign-keys-by/abilities',
    ...options,
  });

/**
 * Query factions rows
 *
 * Returns a paginated list of factions rows with filtering and sorting
 */
export const listFactions = <ThrowOnError extends boolean = false>(
  options: Options<ListFactionsData, ThrowOnError>,
) =>
  (options.client ?? client).post<ListFactionsResponses, ListFactionsErrors, ThrowOnError>({
    security: [
      { scheme: 'bearer', type: 'http' },
      { name: 'X-Api-Key', type: 'apiKey' },
    ],
    url: '/tables/factions/rows',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get factions by ID
 *
 * Returns a single factions row by its ID
 */
export const getFactions = <ThrowOnError extends boolean = false>(
  options: Options<GetFactionsData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetFactionsResponses, GetFactionsErrors, ThrowOnError>({
    security: [
      { scheme: 'bearer', type: 'http' },
      { name: 'X-Api-Key', type: 'apiKey' },
    ],
    url: '/tables/factions/row/{rowId}',
    ...options,
  });

/**
 * Get factions foreign keys by monsters
 *
 * Returns rows from monsters that reference this factions
 */
export const getFactionsForeignKeysByMonsters = <ThrowOnError extends boolean = false>(
  options: Options<GetFactionsForeignKeysByMonstersData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetFactionsForeignKeysByMonstersResponses,
    GetFactionsForeignKeysByMonstersErrors,
    ThrowOnError
  >({
    security: [
      { scheme: 'bearer', type: 'http' },
      { name: 'X-Api-Key', type: 'apiKey' },
    ],
    url: '/tables/factions/row/{rowId}/foreign-keys-by/monsters',
    ...options,
  });

/**
 * Get factions foreign keys by npcs
 *
 * Returns rows from npcs that reference this factions
 */
export const getFactionsForeignKeysByNpcs = <ThrowOnError extends boolean = false>(
  options: Options<GetFactionsForeignKeysByNpcsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetFactionsForeignKeysByNpcsResponses,
    GetFactionsForeignKeysByNpcsErrors,
    ThrowOnError
  >({
    security: [
      { scheme: 'bearer', type: 'http' },
      { name: 'X-Api-Key', type: 'apiKey' },
    ],
    url: '/tables/factions/row/{rowId}/foreign-keys-by/npcs',
    ...options,
  });

/**
 * Query heroes rows
 *
 * Returns a paginated list of heroes rows with filtering and sorting
 */
export const listHeroes = <ThrowOnError extends boolean = false>(
  options: Options<ListHeroesData, ThrowOnError>,
) =>
  (options.client ?? client).post<ListHeroesResponses, ListHeroesErrors, ThrowOnError>({
    security: [
      { scheme: 'bearer', type: 'http' },
      { name: 'X-Api-Key', type: 'apiKey' },
    ],
    url: '/tables/heroes/rows',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get heroes by ID
 *
 * Returns a single heroes row by its ID
 */
export const getHeroes = <ThrowOnError extends boolean = false>(
  options: Options<GetHeroesData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetHeroesResponses, GetHeroesErrors, ThrowOnError>({
    security: [
      { scheme: 'bearer', type: 'http' },
      { name: 'X-Api-Key', type: 'apiKey' },
    ],
    url: '/tables/heroes/row/{rowId}',
    ...options,
  });

/**
 * Get heroes foreign keys by parties
 *
 * Returns rows from parties that reference this heroes
 */
export const getHeroesForeignKeysByParties = <ThrowOnError extends boolean = false>(
  options: Options<GetHeroesForeignKeysByPartiesData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetHeroesForeignKeysByPartiesResponses,
    GetHeroesForeignKeysByPartiesErrors,
    ThrowOnError
  >({
    security: [
      { scheme: 'bearer', type: 'http' },
      { name: 'X-Api-Key', type: 'apiKey' },
    ],
    url: '/tables/heroes/row/{rowId}/foreign-keys-by/parties',
    ...options,
  });

/**
 * Query item_types rows
 *
 * Returns a paginated list of item_types rows with filtering and sorting
 */
export const listItemTypes = <ThrowOnError extends boolean = false>(
  options: Options<ListItemTypesData, ThrowOnError>,
) =>
  (options.client ?? client).post<ListItemTypesResponses, ListItemTypesErrors, ThrowOnError>({
    security: [
      { scheme: 'bearer', type: 'http' },
      { name: 'X-Api-Key', type: 'apiKey' },
    ],
    url: '/tables/item_types/rows',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get item_types by ID
 *
 * Returns a single item_types row by its ID
 */
export const getItemTypes = <ThrowOnError extends boolean = false>(
  options: Options<GetItemTypesData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetItemTypesResponses, GetItemTypesErrors, ThrowOnError>({
    security: [
      { scheme: 'bearer', type: 'http' },
      { name: 'X-Api-Key', type: 'apiKey' },
    ],
    url: '/tables/item_types/row/{rowId}',
    ...options,
  });

/**
 * Get item_types foreign keys by items
 *
 * Returns rows from items that reference this item_types
 */
export const getItemTypesForeignKeysByItems = <ThrowOnError extends boolean = false>(
  options: Options<GetItemTypesForeignKeysByItemsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetItemTypesForeignKeysByItemsResponses,
    GetItemTypesForeignKeysByItemsErrors,
    ThrowOnError
  >({
    security: [
      { scheme: 'bearer', type: 'http' },
      { name: 'X-Api-Key', type: 'apiKey' },
    ],
    url: '/tables/item_types/row/{rowId}/foreign-keys-by/items',
    ...options,
  });

/**
 * Query items rows
 *
 * Returns a paginated list of items rows with filtering and sorting
 */
export const listItems = <ThrowOnError extends boolean = false>(
  options: Options<ListItemsData, ThrowOnError>,
) =>
  (options.client ?? client).post<ListItemsResponses, ListItemsErrors, ThrowOnError>({
    security: [
      { scheme: 'bearer', type: 'http' },
      { name: 'X-Api-Key', type: 'apiKey' },
    ],
    url: '/tables/items/rows',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get items by ID
 *
 * Returns a single items row by its ID
 */
export const getItems = <ThrowOnError extends boolean = false>(
  options: Options<GetItemsData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetItemsResponses, GetItemsErrors, ThrowOnError>({
    security: [
      { scheme: 'bearer', type: 'http' },
      { name: 'X-Api-Key', type: 'apiKey' },
    ],
    url: '/tables/items/row/{rowId}',
    ...options,
  });

/**
 * Get items foreign keys by heroes
 *
 * Returns rows from heroes that reference this items
 */
export const getItemsForeignKeysByHeroes = <ThrowOnError extends boolean = false>(
  options: Options<GetItemsForeignKeysByHeroesData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetItemsForeignKeysByHeroesResponses,
    GetItemsForeignKeysByHeroesErrors,
    ThrowOnError
  >({
    security: [
      { scheme: 'bearer', type: 'http' },
      { name: 'X-Api-Key', type: 'apiKey' },
    ],
    url: '/tables/items/row/{rowId}/foreign-keys-by/heroes',
    ...options,
  });

/**
 * Get items foreign keys by monsters
 *
 * Returns rows from monsters that reference this items
 */
export const getItemsForeignKeysByMonsters = <ThrowOnError extends boolean = false>(
  options: Options<GetItemsForeignKeysByMonstersData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetItemsForeignKeysByMonstersResponses,
    GetItemsForeignKeysByMonstersErrors,
    ThrowOnError
  >({
    security: [
      { scheme: 'bearer', type: 'http' },
      { name: 'X-Api-Key', type: 'apiKey' },
    ],
    url: '/tables/items/row/{rowId}/foreign-keys-by/monsters',
    ...options,
  });

/**
 * Get items foreign keys by npcs
 *
 * Returns rows from npcs that reference this items
 */
export const getItemsForeignKeysByNpcs = <ThrowOnError extends boolean = false>(
  options: Options<GetItemsForeignKeysByNpcsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetItemsForeignKeysByNpcsResponses,
    GetItemsForeignKeysByNpcsErrors,
    ThrowOnError
  >({
    security: [
      { scheme: 'bearer', type: 'http' },
      { name: 'X-Api-Key', type: 'apiKey' },
    ],
    url: '/tables/items/row/{rowId}/foreign-keys-by/npcs',
    ...options,
  });

/**
 * Get items foreign keys by quests
 *
 * Returns rows from quests that reference this items
 */
export const getItemsForeignKeysByQuests = <ThrowOnError extends boolean = false>(
  options: Options<GetItemsForeignKeysByQuestsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetItemsForeignKeysByQuestsResponses,
    GetItemsForeignKeysByQuestsErrors,
    ThrowOnError
  >({
    security: [
      { scheme: 'bearer', type: 'http' },
      { name: 'X-Api-Key', type: 'apiKey' },
    ],
    url: '/tables/items/row/{rowId}/foreign-keys-by/quests',
    ...options,
  });

/**
 * Query locations rows
 *
 * Returns a paginated list of locations rows with filtering and sorting
 */
export const listLocations = <ThrowOnError extends boolean = false>(
  options: Options<ListLocationsData, ThrowOnError>,
) =>
  (options.client ?? client).post<ListLocationsResponses, ListLocationsErrors, ThrowOnError>({
    security: [
      { scheme: 'bearer', type: 'http' },
      { name: 'X-Api-Key', type: 'apiKey' },
    ],
    url: '/tables/locations/rows',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get locations by ID
 *
 * Returns a single locations row by its ID
 */
export const getLocations = <ThrowOnError extends boolean = false>(
  options: Options<GetLocationsData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetLocationsResponses, GetLocationsErrors, ThrowOnError>({
    security: [
      { scheme: 'bearer', type: 'http' },
      { name: 'X-Api-Key', type: 'apiKey' },
    ],
    url: '/tables/locations/row/{rowId}',
    ...options,
  });

/**
 * Get locations foreign keys by npcs
 *
 * Returns rows from npcs that reference this locations
 */
export const getLocationsForeignKeysByNpcs = <ThrowOnError extends boolean = false>(
  options: Options<GetLocationsForeignKeysByNpcsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetLocationsForeignKeysByNpcsResponses,
    GetLocationsForeignKeysByNpcsErrors,
    ThrowOnError
  >({
    security: [
      { scheme: 'bearer', type: 'http' },
      { name: 'X-Api-Key', type: 'apiKey' },
    ],
    url: '/tables/locations/row/{rowId}/foreign-keys-by/npcs',
    ...options,
  });

/**
 * Get locations foreign keys by quests
 *
 * Returns rows from quests that reference this locations
 */
export const getLocationsForeignKeysByQuests = <ThrowOnError extends boolean = false>(
  options: Options<GetLocationsForeignKeysByQuestsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetLocationsForeignKeysByQuestsResponses,
    GetLocationsForeignKeysByQuestsErrors,
    ThrowOnError
  >({
    security: [
      { scheme: 'bearer', type: 'http' },
      { name: 'X-Api-Key', type: 'apiKey' },
    ],
    url: '/tables/locations/row/{rowId}/foreign-keys-by/quests',
    ...options,
  });

/**
 * Query monsters rows
 *
 * Returns a paginated list of monsters rows with filtering and sorting
 */
export const listMonsters = <ThrowOnError extends boolean = false>(
  options: Options<ListMonstersData, ThrowOnError>,
) =>
  (options.client ?? client).post<ListMonstersResponses, ListMonstersErrors, ThrowOnError>({
    security: [
      { scheme: 'bearer', type: 'http' },
      { name: 'X-Api-Key', type: 'apiKey' },
    ],
    url: '/tables/monsters/rows',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get monsters by ID
 *
 * Returns a single monsters row by its ID
 */
export const getMonsters = <ThrowOnError extends boolean = false>(
  options: Options<GetMonstersData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetMonstersResponses, GetMonstersErrors, ThrowOnError>({
    security: [
      { scheme: 'bearer', type: 'http' },
      { name: 'X-Api-Key', type: 'apiKey' },
    ],
    url: '/tables/monsters/row/{rowId}',
    ...options,
  });

/**
 * Query npcs rows
 *
 * Returns a paginated list of npcs rows with filtering and sorting
 */
export const listNpcs = <ThrowOnError extends boolean = false>(
  options: Options<ListNpcsData, ThrowOnError>,
) =>
  (options.client ?? client).post<ListNpcsResponses, ListNpcsErrors, ThrowOnError>({
    security: [
      { scheme: 'bearer', type: 'http' },
      { name: 'X-Api-Key', type: 'apiKey' },
    ],
    url: '/tables/npcs/rows',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get npcs by ID
 *
 * Returns a single npcs row by its ID
 */
export const getNpcs = <ThrowOnError extends boolean = false>(
  options: Options<GetNpcsData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetNpcsResponses, GetNpcsErrors, ThrowOnError>({
    security: [
      { scheme: 'bearer', type: 'http' },
      { name: 'X-Api-Key', type: 'apiKey' },
    ],
    url: '/tables/npcs/row/{rowId}',
    ...options,
  });

/**
 * Get npcs foreign keys by dialogs
 *
 * Returns rows from dialogs that reference this npcs
 */
export const getNpcsForeignKeysByDialogs = <ThrowOnError extends boolean = false>(
  options: Options<GetNpcsForeignKeysByDialogsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetNpcsForeignKeysByDialogsResponses,
    GetNpcsForeignKeysByDialogsErrors,
    ThrowOnError
  >({
    security: [
      { scheme: 'bearer', type: 'http' },
      { name: 'X-Api-Key', type: 'apiKey' },
    ],
    url: '/tables/npcs/row/{rowId}/foreign-keys-by/dialogs',
    ...options,
  });

/**
 * Get npcs foreign keys by quests
 *
 * Returns rows from quests that reference this npcs
 */
export const getNpcsForeignKeysByQuests = <ThrowOnError extends boolean = false>(
  options: Options<GetNpcsForeignKeysByQuestsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetNpcsForeignKeysByQuestsResponses,
    GetNpcsForeignKeysByQuestsErrors,
    ThrowOnError
  >({
    security: [
      { scheme: 'bearer', type: 'http' },
      { name: 'X-Api-Key', type: 'apiKey' },
    ],
    url: '/tables/npcs/row/{rowId}/foreign-keys-by/quests',
    ...options,
  });

/**
 * Query parties rows
 *
 * Returns a paginated list of parties rows with filtering and sorting
 */
export const listParties = <ThrowOnError extends boolean = false>(
  options: Options<ListPartiesData, ThrowOnError>,
) =>
  (options.client ?? client).post<ListPartiesResponses, ListPartiesErrors, ThrowOnError>({
    security: [
      { scheme: 'bearer', type: 'http' },
      { name: 'X-Api-Key', type: 'apiKey' },
    ],
    url: '/tables/parties/rows',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get parties by ID
 *
 * Returns a single parties row by its ID
 */
export const getParties = <ThrowOnError extends boolean = false>(
  options: Options<GetPartiesData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetPartiesResponses, GetPartiesErrors, ThrowOnError>({
    security: [
      { scheme: 'bearer', type: 'http' },
      { name: 'X-Api-Key', type: 'apiKey' },
    ],
    url: '/tables/parties/row/{rowId}',
    ...options,
  });

/**
 * Query quests rows
 *
 * Returns a paginated list of quests rows with filtering and sorting
 */
export const listQuests = <ThrowOnError extends boolean = false>(
  options: Options<ListQuestsData, ThrowOnError>,
) =>
  (options.client ?? client).post<ListQuestsResponses, ListQuestsErrors, ThrowOnError>({
    security: [
      { scheme: 'bearer', type: 'http' },
      { name: 'X-Api-Key', type: 'apiKey' },
    ],
    url: '/tables/quests/rows',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get quests by ID
 *
 * Returns a single quests row by its ID
 */
export const getQuests = <ThrowOnError extends boolean = false>(
  options: Options<GetQuestsData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetQuestsResponses, GetQuestsErrors, ThrowOnError>({
    security: [
      { scheme: 'bearer', type: 'http' },
      { name: 'X-Api-Key', type: 'apiKey' },
    ],
    url: '/tables/quests/row/{rowId}',
    ...options,
  });

/**
 * Query regions rows
 *
 * Returns a paginated list of regions rows with filtering and sorting
 */
export const listRegions = <ThrowOnError extends boolean = false>(
  options: Options<ListRegionsData, ThrowOnError>,
) =>
  (options.client ?? client).post<ListRegionsResponses, ListRegionsErrors, ThrowOnError>({
    security: [
      { scheme: 'bearer', type: 'http' },
      { name: 'X-Api-Key', type: 'apiKey' },
    ],
    url: '/tables/regions/rows',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get regions by ID
 *
 * Returns a single regions row by its ID
 */
export const getRegions = <ThrowOnError extends boolean = false>(
  options: Options<GetRegionsData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetRegionsResponses, GetRegionsErrors, ThrowOnError>({
    security: [
      { scheme: 'bearer', type: 'http' },
      { name: 'X-Api-Key', type: 'apiKey' },
    ],
    url: '/tables/regions/row/{rowId}',
    ...options,
  });

/**
 * Get regions foreign keys by locations
 *
 * Returns rows from locations that reference this regions
 */
export const getRegionsForeignKeysByLocations = <ThrowOnError extends boolean = false>(
  options: Options<GetRegionsForeignKeysByLocationsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetRegionsForeignKeysByLocationsResponses,
    GetRegionsForeignKeysByLocationsErrors,
    ThrowOnError
  >({
    security: [
      { scheme: 'bearer', type: 'http' },
      { name: 'X-Api-Key', type: 'apiKey' },
    ],
    url: '/tables/regions/row/{rowId}/foreign-keys-by/locations',
    ...options,
  });

/**
 * Query stats rows
 *
 * Returns a paginated list of stats rows with filtering and sorting
 */
export const listStats = <ThrowOnError extends boolean = false>(
  options: Options<ListStatsData, ThrowOnError>,
) =>
  (options.client ?? client).post<ListStatsResponses, ListStatsErrors, ThrowOnError>({
    security: [
      { scheme: 'bearer', type: 'http' },
      { name: 'X-Api-Key', type: 'apiKey' },
    ],
    url: '/tables/stats/rows',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get stats by ID
 *
 * Returns a single stats row by its ID
 */
export const getStats = <ThrowOnError extends boolean = false>(
  options: Options<GetStatsData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetStatsResponses, GetStatsErrors, ThrowOnError>({
    security: [
      { scheme: 'bearer', type: 'http' },
      { name: 'X-Api-Key', type: 'apiKey' },
    ],
    url: '/tables/stats/row/{rowId}',
    ...options,
  });

/**
 * Get stats foreign keys by items
 *
 * Returns rows from items that reference this stats
 */
export const getStatsForeignKeysByItems = <ThrowOnError extends boolean = false>(
  options: Options<GetStatsForeignKeysByItemsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetStatsForeignKeysByItemsResponses,
    GetStatsForeignKeysByItemsErrors,
    ThrowOnError
  >({
    security: [
      { scheme: 'bearer', type: 'http' },
      { name: 'X-Api-Key', type: 'apiKey' },
    ],
    url: '/tables/stats/row/{rowId}/foreign-keys-by/items',
    ...options,
  });
