// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}/endpoint/rest/admin/demo-rpg-data/master/head` | (string & {});
};

/**
 * String filter conditions
 */
export type DemoRpgDataStringFilter = {
  equals?: string;
  in?: Array<string>;
  notIn?: Array<string>;
  lt?: string;
  lte?: string;
  gt?: string;
  gte?: string;
  contains?: string;
  startsWith?: string;
  endsWith?: string;
  mode?: 'default' | 'insensitive';
  not?: string;
};

/**
 * Boolean filter conditions
 */
export type DemoRpgDataBoolFilter = {
  equals?: boolean;
  not?: boolean;
};

/**
 * DateTime filter conditions
 */
export type DemoRpgDataDateTimeFilter = {
  equals?: string;
  in?: Array<string>;
  notIn?: Array<string>;
  lt?: string;
  lte?: string;
  gt?: string;
  gte?: string;
};

/**
 * JSON filter conditions for data field
 */
export type DemoRpgDataJsonFilter = {
  equals?: {
    [key: string]: unknown;
  };
  /**
   * Path in JSON (e.g., "user.name" or ["user", "name"])
   */
  path?: string | Array<string>;
  mode?: 'default' | 'insensitive';
  string_contains?: string;
  string_starts_with?: string;
  string_ends_with?: string;
  array_contains?: Array<{
    [key: string]: unknown;
  }>;
  array_starts_with?: {
    [key: string]: unknown;
  };
  array_ends_with?: {
    [key: string]: unknown;
  };
  lt?: number;
  lte?: number;
  gt?: number;
  gte?: number;
  /**
   * Full-text search string
   */
  search?: string;
  /**
   * Language for full-text search
   */
  searchLanguage?:
    | 'simple'
    | 'arabic'
    | 'armenian'
    | 'basque'
    | 'catalan'
    | 'danish'
    | 'dutch'
    | 'english'
    | 'finnish'
    | 'french'
    | 'german'
    | 'greek'
    | 'hindi'
    | 'hungarian'
    | 'indonesian'
    | 'irish'
    | 'italian'
    | 'lithuanian'
    | 'nepali'
    | 'norwegian'
    | 'portuguese'
    | 'romanian'
    | 'russian'
    | 'serbian'
    | 'spanish'
    | 'swedish'
    | 'tamil'
    | 'turkish'
    | 'yiddish';
  searchType?: 'plain' | 'phrase' | 'prefix' | 'tsquery';
  searchIn?: 'all' | 'values' | 'keys' | 'strings' | 'numbers' | 'booleans';
};

/**
 * Row filtering conditions
 */
export type DemoRpgDataRowWhereInput = {
  /**
   * AND conditions
   */
  AND?: Array<DemoRpgDataRowWhereInput>;
  /**
   * OR conditions
   */
  OR?: Array<DemoRpgDataRowWhereInput>;
  /**
   * NOT conditions
   */
  NOT?: Array<DemoRpgDataRowWhereInput>;
  id?: DemoRpgDataStringFilter;
  versionId?: DemoRpgDataStringFilter;
  createdId?: DemoRpgDataStringFilter;
  readonly?: DemoRpgDataBoolFilter;
  createdAt?: DemoRpgDataDateTimeFilter;
  updatedAt?: DemoRpgDataDateTimeFilter;
  publishedAt?: DemoRpgDataDateTimeFilter;
  data?: DemoRpgDataJsonFilter;
  meta?: DemoRpgDataJsonFilter;
  hash?: DemoRpgDataStringFilter;
  schemaHash?: DemoRpgDataStringFilter;
};

/**
 * Sorting criteria
 */
export type DemoRpgDataOrderBy = {
  /**
   * Field to sort by
   */
  field: 'createdAt' | 'updatedAt' | 'publishedAt' | 'id' | 'data';
  /**
   * Sort direction
   */
  direction: 'asc' | 'desc';
  /**
   * Path within data field for nested sorting (e.g., "user.age")
   */
  path?: string;
  /**
   * Data type for sorting when using data field
   */
  type?: 'text' | 'int' | 'float' | 'boolean' | 'timestamp';
  /**
   * Aggregation function for array fields
   */
  aggregation?: 'min' | 'max' | 'avg' | 'first' | 'last';
};

/**
 * JSON Patch operation (RFC 6902 subset - only replace)
 */
export type DemoRpgDataPatchOperation = {
  /**
   * Operation type (only "replace" is supported)
   */
  op: 'replace';
  /**
   * JSON path using dot notation for objects and [index] for arrays (e.g., "name", "user.email", "items[0]")
   */
  path: string;
  /**
   * The value to set at the specified path (any valid JSON value)
   */
  value: unknown;
};

export type DemoRpgDataAbilities = {
  icon: {
    readonly status: string;
    readonly fileId: string;
    readonly url: string;
    fileName: string;
    readonly hash: string;
    readonly extension: string;
    readonly mimeType: string;
    readonly size: number;
    readonly width: number;
    readonly height: number;
  };
  kind: 'active' | 'passive' | 'reaction';
  name: {
    en: string;
    ru: string;
    zh: string;
  };
  school:
    | 'abjuration'
    | 'conjuration'
    | 'divination'
    | 'enchantment'
    | 'evocation'
    | 'illusion'
    | 'necromancy'
    | 'transmutation';
  effects: Array<{
    chance: number;
    duration: number;
    effect_id: string;
  }>;
  cooldown: number;
  base_damage: number;
  description: {
    en: string;
    ru: string;
    zh: string;
  };
  damage_scaling: number;
  level_required: number;
};

export type DemoRpgDataClasses = {
  name: {
    en: string;
    ru: string;
    zh: string;
  };
  base_hp: number;
  description: {
    en: string;
    ru: string;
    zh: string;
  };
  hp_per_level: number;
  mp_per_level: number;
  primary_stat: 'strength' | 'dexterity' | 'intelligence' | 'wisdom' | 'constitution' | 'charisma';
  starting_ability_ids: Array<string>;
};

export type DemoRpgDataDialogs = {
  slug: string;
  lines: Array<{
    text: {
      en: string;
      ru: string;
      zh: string;
    };
    emotion: 'neutral' | 'happy' | 'angry' | 'sad' | 'surprised';
    speaker: 'npc' | 'hero';
  }>;
  npc_id: string;
  readonly line_count: number;
};

export type DemoRpgDataEffects = {
  code: string;
  kind: 'buff' | 'debuff' | 'damage_over_time' | 'crowd_control';
  name: {
    en: string;
    ru: string;
    zh: string;
  };
  description: {
    en: string;
    ru: string;
    zh: string;
  };
  default_duration: number;
};

export type DemoRpgDataFactions = {
  name: {
    en: string;
    ru: string;
    zh: string;
  };
  crest: {
    readonly status: string;
    readonly fileId: string;
    readonly url: string;
    fileName: string;
    readonly hash: string;
    readonly extension: string;
    readonly mimeType: string;
    readonly size: number;
    readonly width: number;
    readonly height: number;
  };
  alignment: 'lawful_good' | 'lawful_neutral' | 'neutral' | 'chaotic_neutral' | 'chaotic_evil';
  description: {
    en: string;
    ru: string;
    zh: string;
  };
};

export type DemoRpgDataHeroes = {
  gold: number;
  name: {
    en: string;
    ru: string;
    zh: string;
  };
  level: number;
  epithet: {
    en: string;
    ru: string;
    zh: string;
  };
  class_id: string;
  portrait: {
    readonly status: string;
    readonly fileId: string;
    readonly url: string;
    fileName: string;
    readonly hash: string;
    readonly extension: string;
    readonly mimeType: string;
    readonly size: number;
    readonly width: number;
    readonly height: number;
  };
  equipment: Array<{
    slot: 'head' | 'chest' | 'legs' | 'hands' | 'feet' | 'main_hand' | 'off_hand' | 'ranged';
    item_id: string;
    modifier: number;
  }>;
  readonly is_veteran: boolean;
  ability_ids: Array<string>;
  constitution: number;
  readonly equipped_count: number;
  readonly display_name_en: string;
  inventory_item_ids: Array<string>;
  readonly total_equipment_modifier: number;
};

export type DemoRpgDataItemTypes = {
  code: string;
  name: {
    en: string;
    ru: string;
    zh: string;
  };
  description: {
    en: string;
    ru: string;
    zh: string;
  };
};

export type DemoRpgDataItems = {
  icon: {
    readonly status: string;
    readonly fileId: string;
    readonly url: string;
    fileName: string;
    readonly hash: string;
    readonly extension: string;
    readonly mimeType: string;
    readonly size: number;
    readonly width: number;
    readonly height: number;
  };
  name: {
    en: string;
    ru: string;
    zh: string;
  };
  rarity: 'common' | 'uncommon' | 'rare' | 'epic' | 'legendary';
  weight: number;
  type_id: string;
  modifiers: Array<{
    value: number;
    stat_id: string;
  }>;
  base_value: number;
  readonly rarity_tag: string;
  description: {
    en: string;
    ru: string;
    zh: string;
  };
  readonly market_value: number;
  rarity_multiplier: number;
};

export type DemoRpgDataLocations = {
  map: {
    readonly status: string;
    readonly fileId: string;
    readonly url: string;
    fileName: string;
    readonly hash: string;
    readonly extension: string;
    readonly mimeType: string;
    readonly size: number;
    readonly width: number;
    readonly height: number;
  };
  kind: 'town' | 'village' | 'dungeon' | 'ruin' | 'wilderness';
  name: {
    en: string;
    ru: string;
    zh: string;
  };
  region_id: string;
  coordinates: {
    x: number;
    y: number;
  };
  description: {
    en: string;
    ru: string;
    zh: string;
  };
};

export type DemoRpgDataMonsters = {
  hp: number;
  kind: 'beast' | 'humanoid' | 'undead' | 'aberration' | 'construct';
  name: {
    en: string;
    ru: string;
    zh: string;
  };
  drops: Array<{
    chance: number;
    item_id: string;
    quantity_max: number;
    quantity_min: number;
  }>;
  image: {
    readonly status: string;
    readonly fileId: string;
    readonly url: string;
    fileName: string;
    readonly hash: string;
    readonly extension: string;
    readonly mimeType: string;
    readonly size: number;
    readonly width: number;
    readonly height: number;
  };
  level: number;
  readonly drop_count: number;
  faction_id: string;
  ability_ids: Array<string>;
  base_damage: number;
  description: {
    en: string;
    ru: string;
    zh: string;
  };
  readonly avg_drop_chance: number;
};

export type DemoRpgDataNpcs = {
  name: {
    en: string;
    ru: string;
    zh: string;
  };
  role: 'quest_giver' | 'merchant' | 'trainer' | 'lore_keeper';
  title: {
    en: string;
    ru: string;
    zh: string;
  };
  portrait: {
    readonly status: string;
    readonly fileId: string;
    readonly url: string;
    fileName: string;
    readonly hash: string;
    readonly extension: string;
    readonly mimeType: string;
    readonly size: number;
    readonly width: number;
    readonly height: number;
  };
  faction_id: string;
  description: {
    en: string;
    ru: string;
    zh: string;
  };
  location_id: string;
  readonly display_label_en: string;
  inventory_item_ids: Array<string>;
};

export type DemoRpgDataParties = {
  name: {
    en: string;
    ru: string;
    zh: string;
  };
  motto: {
    en: string;
    ru: string;
    zh: string;
  };
  readonly is_full: boolean;
  hero_ids: Array<string>;
  formation: 'vanguard' | 'balanced' | 'defensive' | 'skirmisher';
  readonly member_count: number;
};

export type DemoRpgDataQuests = {
  map: {
    readonly status: string;
    readonly fileId: string;
    readonly url: string;
    fileName: string;
    readonly hash: string;
    readonly extension: string;
    readonly mimeType: string;
    readonly size: number;
    readonly width: number;
    readonly height: number;
  };
  kind: 'tutorial' | 'side' | 'story' | 'endgame';
  name: {
    en: string;
    ru: string;
    zh: string;
  };
  steps: Array<{
    xp: number;
    npc_id: string;
    rewards: Array<{
      item_id: string;
      bonus_xp: number;
      quantity: number;
    }>;
    description: {
      en: string;
      ru: string;
      zh: string;
    };
    location_id: string;
    step_number: number;
  }>;
  readonly total_xp: number;
  readonly step_count: number;
  description: {
    en: string;
    ru: string;
    zh: string;
  };
  giver_npc_id: string;
  is_repeatable: boolean;
  readonly total_loot_xp: number;
  level_required: number;
};

export type DemoRpgDataRegions = {
  name: {
    en: string;
    ru: string;
    zh: string;
  };
  climate: 'temperate' | 'alpine' | 'coastal' | 'desert' | 'forest';
  description: {
    en: string;
    ru: string;
    zh: string;
  };
};

export type DemoRpgDataStats = {
  code: string;
  name: {
    en: string;
    ru: string;
    zh: string;
  };
  description: {
    en: string;
    ru: string;
    zh: string;
  };
  abbreviation: string;
};

export type DemoRpgDataAbilitiesWritable = {
  icon: {
    fileName: string;
  };
  kind: 'active' | 'passive' | 'reaction';
  name: {
    en: string;
    ru: string;
    zh: string;
  };
  school:
    | 'abjuration'
    | 'conjuration'
    | 'divination'
    | 'enchantment'
    | 'evocation'
    | 'illusion'
    | 'necromancy'
    | 'transmutation';
  effects: Array<{
    chance: number;
    duration: number;
    effect_id: string;
  }>;
  cooldown: number;
  base_damage: number;
  description: {
    en: string;
    ru: string;
    zh: string;
  };
  damage_scaling: number;
  level_required: number;
};

export type DemoRpgDataDialogsWritable = {
  slug: string;
  lines: Array<{
    text: {
      en: string;
      ru: string;
      zh: string;
    };
    emotion: 'neutral' | 'happy' | 'angry' | 'sad' | 'surprised';
    speaker: 'npc' | 'hero';
  }>;
  npc_id: string;
};

export type DemoRpgDataFactionsWritable = {
  name: {
    en: string;
    ru: string;
    zh: string;
  };
  crest: {
    fileName: string;
  };
  alignment: 'lawful_good' | 'lawful_neutral' | 'neutral' | 'chaotic_neutral' | 'chaotic_evil';
  description: {
    en: string;
    ru: string;
    zh: string;
  };
};

export type DemoRpgDataHeroesWritable = {
  gold: number;
  name: {
    en: string;
    ru: string;
    zh: string;
  };
  level: number;
  epithet: {
    en: string;
    ru: string;
    zh: string;
  };
  class_id: string;
  portrait: {
    fileName: string;
  };
  equipment: Array<{
    slot: 'head' | 'chest' | 'legs' | 'hands' | 'feet' | 'main_hand' | 'off_hand' | 'ranged';
    item_id: string;
    modifier: number;
  }>;
  ability_ids: Array<string>;
  constitution: number;
  inventory_item_ids: Array<string>;
};

export type DemoRpgDataItemsWritable = {
  icon: {
    fileName: string;
  };
  name: {
    en: string;
    ru: string;
    zh: string;
  };
  rarity: 'common' | 'uncommon' | 'rare' | 'epic' | 'legendary';
  weight: number;
  type_id: string;
  modifiers: Array<{
    value: number;
    stat_id: string;
  }>;
  base_value: number;
  description: {
    en: string;
    ru: string;
    zh: string;
  };
  rarity_multiplier: number;
};

export type DemoRpgDataLocationsWritable = {
  map: {
    fileName: string;
  };
  kind: 'town' | 'village' | 'dungeon' | 'ruin' | 'wilderness';
  name: {
    en: string;
    ru: string;
    zh: string;
  };
  region_id: string;
  coordinates: {
    x: number;
    y: number;
  };
  description: {
    en: string;
    ru: string;
    zh: string;
  };
};

export type DemoRpgDataMonstersWritable = {
  hp: number;
  kind: 'beast' | 'humanoid' | 'undead' | 'aberration' | 'construct';
  name: {
    en: string;
    ru: string;
    zh: string;
  };
  drops: Array<{
    chance: number;
    item_id: string;
    quantity_max: number;
    quantity_min: number;
  }>;
  image: {
    fileName: string;
  };
  level: number;
  faction_id: string;
  ability_ids: Array<string>;
  base_damage: number;
  description: {
    en: string;
    ru: string;
    zh: string;
  };
};

export type DemoRpgDataNpcsWritable = {
  name: {
    en: string;
    ru: string;
    zh: string;
  };
  role: 'quest_giver' | 'merchant' | 'trainer' | 'lore_keeper';
  title: {
    en: string;
    ru: string;
    zh: string;
  };
  portrait: {
    fileName: string;
  };
  faction_id: string;
  description: {
    en: string;
    ru: string;
    zh: string;
  };
  location_id: string;
  inventory_item_ids: Array<string>;
};

export type DemoRpgDataPartiesWritable = {
  name: {
    en: string;
    ru: string;
    zh: string;
  };
  motto: {
    en: string;
    ru: string;
    zh: string;
  };
  hero_ids: Array<string>;
  formation: 'vanguard' | 'balanced' | 'defensive' | 'skirmisher';
};

export type DemoRpgDataQuestsWritable = {
  map: {
    fileName: string;
  };
  kind: 'tutorial' | 'side' | 'story' | 'endgame';
  name: {
    en: string;
    ru: string;
    zh: string;
  };
  steps: Array<{
    xp: number;
    npc_id: string;
    rewards: Array<{
      item_id: string;
      bonus_xp: number;
      quantity: number;
    }>;
    description: {
      en: string;
      ru: string;
      zh: string;
    };
    location_id: string;
    step_number: number;
  }>;
  description: {
    en: string;
    ru: string;
    zh: string;
  };
  giver_npc_id: string;
  is_repeatable: boolean;
  level_required: number;
};

export type ListAbilitiesData = {
  /**
   * Query parameters for filtering and pagination
   */
  body: {
    /**
     * Number of items to return
     */
    first: number;
    /**
     * Cursor for pagination
     */
    after?: string;
    /**
     * Array of sorting criteria
     */
    orderBy?: Array<DemoRpgDataOrderBy>;
    /**
     * Filter conditions
     */
    where?: DemoRpgDataRowWhereInput;
  };
  path?: never;
  query?: never;
  url: '/tables/abilities/rows';
};

export type ListAbilitiesErrors = {
  /**
   * Unauthorized - invalid or missing access token or API key
   */
  401: unknown;
};

export type ListAbilitiesResponses = {
  /**
   * Paginated list of rows
   */
  200: {
    edges: Array<{
      cursor: string;
      node: {
        /**
         * Row ID
         */
        id: string;
        /**
         * Current version ID
         */
        versionId: string;
        /**
         * Original creation ID
         */
        createdId: string;
        /**
         * Creation timestamp
         */
        createdAt: string;
        /**
         * Last update timestamp
         */
        updatedAt: string;
        /**
         * Publication timestamp
         */
        publishedAt: string;
        /**
         * Whether the row is read-only
         */
        readonly: boolean;
        data: DemoRpgDataAbilities;
      };
    }>;
    pageInfo: {
      startCursor: string | null;
      endCursor: string | null;
      hasNextPage: boolean;
      hasPreviousPage: boolean;
    };
    totalCount: number;
  };
};

export type ListAbilitiesResponse = ListAbilitiesResponses[keyof ListAbilitiesResponses];

export type GetAbilitiesData = {
  body?: never;
  path: {
    /**
     * Row ID
     */
    rowId: string;
  };
  query?: never;
  url: '/tables/abilities/row/{rowId}';
};

export type GetAbilitiesErrors = {
  /**
   * Unauthorized - invalid or missing access token or API key
   */
  401: unknown;
  /**
   * Not found
   */
  404: unknown;
};

export type GetAbilitiesResponses = {
  /**
   * Successful response
   */
  200: {
    /**
     * Row ID
     */
    id: string;
    /**
     * Current version ID
     */
    versionId: string;
    /**
     * Original creation ID
     */
    createdId: string;
    /**
     * Creation timestamp
     */
    createdAt: string;
    /**
     * Last update timestamp
     */
    updatedAt: string;
    /**
     * Publication timestamp
     */
    publishedAt: string;
    /**
     * Whether the row is read-only
     */
    readonly: boolean;
    data: DemoRpgDataAbilities;
  };
};

export type GetAbilitiesResponse = GetAbilitiesResponses[keyof GetAbilitiesResponses];

export type GetAbilitiesForeignKeysByClassesData = {
  body?: never;
  path: {
    /**
     * Row ID
     */
    rowId: string;
  };
  query: {
    /**
     * Number of items to return
     */
    first: number;
    /**
     * Cursor for pagination
     */
    after?: string;
  };
  url: '/tables/abilities/row/{rowId}/foreign-keys-by/classes';
};

export type GetAbilitiesForeignKeysByClassesErrors = {
  /**
   * Unauthorized - invalid or missing access token or API key
   */
  401: unknown;
  /**
   * Not found
   */
  404: unknown;
};

export type GetAbilitiesForeignKeysByClassesResponses = {
  /**
   * Paginated list of related rows
   */
  200: {
    edges: Array<{
      cursor: string;
      node: {
        /**
         * Row ID
         */
        id: string;
        /**
         * Current version ID
         */
        versionId: string;
        /**
         * Original creation ID
         */
        createdId: string;
        /**
         * Creation timestamp
         */
        createdAt: string;
        /**
         * Last update timestamp
         */
        updatedAt: string;
        /**
         * Publication timestamp
         */
        publishedAt: string;
        /**
         * Whether the row is read-only
         */
        readonly: boolean;
        data: DemoRpgDataClasses;
      };
    }>;
    pageInfo: {
      startCursor: string | null;
      endCursor: string | null;
      hasNextPage: boolean;
      hasPreviousPage: boolean;
    };
    totalCount: number;
  };
};

export type GetAbilitiesForeignKeysByClassesResponse =
  GetAbilitiesForeignKeysByClassesResponses[keyof GetAbilitiesForeignKeysByClassesResponses];

export type GetAbilitiesForeignKeysByHeroesData = {
  body?: never;
  path: {
    /**
     * Row ID
     */
    rowId: string;
  };
  query: {
    /**
     * Number of items to return
     */
    first: number;
    /**
     * Cursor for pagination
     */
    after?: string;
  };
  url: '/tables/abilities/row/{rowId}/foreign-keys-by/heroes';
};

export type GetAbilitiesForeignKeysByHeroesErrors = {
  /**
   * Unauthorized - invalid or missing access token or API key
   */
  401: unknown;
  /**
   * Not found
   */
  404: unknown;
};

export type GetAbilitiesForeignKeysByHeroesResponses = {
  /**
   * Paginated list of related rows
   */
  200: {
    edges: Array<{
      cursor: string;
      node: {
        /**
         * Row ID
         */
        id: string;
        /**
         * Current version ID
         */
        versionId: string;
        /**
         * Original creation ID
         */
        createdId: string;
        /**
         * Creation timestamp
         */
        createdAt: string;
        /**
         * Last update timestamp
         */
        updatedAt: string;
        /**
         * Publication timestamp
         */
        publishedAt: string;
        /**
         * Whether the row is read-only
         */
        readonly: boolean;
        data: DemoRpgDataHeroes;
      };
    }>;
    pageInfo: {
      startCursor: string | null;
      endCursor: string | null;
      hasNextPage: boolean;
      hasPreviousPage: boolean;
    };
    totalCount: number;
  };
};

export type GetAbilitiesForeignKeysByHeroesResponse =
  GetAbilitiesForeignKeysByHeroesResponses[keyof GetAbilitiesForeignKeysByHeroesResponses];

export type GetAbilitiesForeignKeysByMonstersData = {
  body?: never;
  path: {
    /**
     * Row ID
     */
    rowId: string;
  };
  query: {
    /**
     * Number of items to return
     */
    first: number;
    /**
     * Cursor for pagination
     */
    after?: string;
  };
  url: '/tables/abilities/row/{rowId}/foreign-keys-by/monsters';
};

export type GetAbilitiesForeignKeysByMonstersErrors = {
  /**
   * Unauthorized - invalid or missing access token or API key
   */
  401: unknown;
  /**
   * Not found
   */
  404: unknown;
};

export type GetAbilitiesForeignKeysByMonstersResponses = {
  /**
   * Paginated list of related rows
   */
  200: {
    edges: Array<{
      cursor: string;
      node: {
        /**
         * Row ID
         */
        id: string;
        /**
         * Current version ID
         */
        versionId: string;
        /**
         * Original creation ID
         */
        createdId: string;
        /**
         * Creation timestamp
         */
        createdAt: string;
        /**
         * Last update timestamp
         */
        updatedAt: string;
        /**
         * Publication timestamp
         */
        publishedAt: string;
        /**
         * Whether the row is read-only
         */
        readonly: boolean;
        data: DemoRpgDataMonsters;
      };
    }>;
    pageInfo: {
      startCursor: string | null;
      endCursor: string | null;
      hasNextPage: boolean;
      hasPreviousPage: boolean;
    };
    totalCount: number;
  };
};

export type GetAbilitiesForeignKeysByMonstersResponse =
  GetAbilitiesForeignKeysByMonstersResponses[keyof GetAbilitiesForeignKeysByMonstersResponses];

export type ListClassesData = {
  /**
   * Query parameters for filtering and pagination
   */
  body: {
    /**
     * Number of items to return
     */
    first: number;
    /**
     * Cursor for pagination
     */
    after?: string;
    /**
     * Array of sorting criteria
     */
    orderBy?: Array<DemoRpgDataOrderBy>;
    /**
     * Filter conditions
     */
    where?: DemoRpgDataRowWhereInput;
  };
  path?: never;
  query?: never;
  url: '/tables/classes/rows';
};

export type ListClassesErrors = {
  /**
   * Unauthorized - invalid or missing access token or API key
   */
  401: unknown;
};

export type ListClassesResponses = {
  /**
   * Paginated list of rows
   */
  200: {
    edges: Array<{
      cursor: string;
      node: {
        /**
         * Row ID
         */
        id: string;
        /**
         * Current version ID
         */
        versionId: string;
        /**
         * Original creation ID
         */
        createdId: string;
        /**
         * Creation timestamp
         */
        createdAt: string;
        /**
         * Last update timestamp
         */
        updatedAt: string;
        /**
         * Publication timestamp
         */
        publishedAt: string;
        /**
         * Whether the row is read-only
         */
        readonly: boolean;
        data: DemoRpgDataClasses;
      };
    }>;
    pageInfo: {
      startCursor: string | null;
      endCursor: string | null;
      hasNextPage: boolean;
      hasPreviousPage: boolean;
    };
    totalCount: number;
  };
};

export type ListClassesResponse = ListClassesResponses[keyof ListClassesResponses];

export type GetClassesData = {
  body?: never;
  path: {
    /**
     * Row ID
     */
    rowId: string;
  };
  query?: never;
  url: '/tables/classes/row/{rowId}';
};

export type GetClassesErrors = {
  /**
   * Unauthorized - invalid or missing access token or API key
   */
  401: unknown;
  /**
   * Not found
   */
  404: unknown;
};

export type GetClassesResponses = {
  /**
   * Successful response
   */
  200: {
    /**
     * Row ID
     */
    id: string;
    /**
     * Current version ID
     */
    versionId: string;
    /**
     * Original creation ID
     */
    createdId: string;
    /**
     * Creation timestamp
     */
    createdAt: string;
    /**
     * Last update timestamp
     */
    updatedAt: string;
    /**
     * Publication timestamp
     */
    publishedAt: string;
    /**
     * Whether the row is read-only
     */
    readonly: boolean;
    data: DemoRpgDataClasses;
  };
};

export type GetClassesResponse = GetClassesResponses[keyof GetClassesResponses];

export type GetClassesForeignKeysByHeroesData = {
  body?: never;
  path: {
    /**
     * Row ID
     */
    rowId: string;
  };
  query: {
    /**
     * Number of items to return
     */
    first: number;
    /**
     * Cursor for pagination
     */
    after?: string;
  };
  url: '/tables/classes/row/{rowId}/foreign-keys-by/heroes';
};

export type GetClassesForeignKeysByHeroesErrors = {
  /**
   * Unauthorized - invalid or missing access token or API key
   */
  401: unknown;
  /**
   * Not found
   */
  404: unknown;
};

export type GetClassesForeignKeysByHeroesResponses = {
  /**
   * Paginated list of related rows
   */
  200: {
    edges: Array<{
      cursor: string;
      node: {
        /**
         * Row ID
         */
        id: string;
        /**
         * Current version ID
         */
        versionId: string;
        /**
         * Original creation ID
         */
        createdId: string;
        /**
         * Creation timestamp
         */
        createdAt: string;
        /**
         * Last update timestamp
         */
        updatedAt: string;
        /**
         * Publication timestamp
         */
        publishedAt: string;
        /**
         * Whether the row is read-only
         */
        readonly: boolean;
        data: DemoRpgDataHeroes;
      };
    }>;
    pageInfo: {
      startCursor: string | null;
      endCursor: string | null;
      hasNextPage: boolean;
      hasPreviousPage: boolean;
    };
    totalCount: number;
  };
};

export type GetClassesForeignKeysByHeroesResponse =
  GetClassesForeignKeysByHeroesResponses[keyof GetClassesForeignKeysByHeroesResponses];

export type ListDialogsData = {
  /**
   * Query parameters for filtering and pagination
   */
  body: {
    /**
     * Number of items to return
     */
    first: number;
    /**
     * Cursor for pagination
     */
    after?: string;
    /**
     * Array of sorting criteria
     */
    orderBy?: Array<DemoRpgDataOrderBy>;
    /**
     * Filter conditions
     */
    where?: DemoRpgDataRowWhereInput;
  };
  path?: never;
  query?: never;
  url: '/tables/dialogs/rows';
};

export type ListDialogsErrors = {
  /**
   * Unauthorized - invalid or missing access token or API key
   */
  401: unknown;
};

export type ListDialogsResponses = {
  /**
   * Paginated list of rows
   */
  200: {
    edges: Array<{
      cursor: string;
      node: {
        /**
         * Row ID
         */
        id: string;
        /**
         * Current version ID
         */
        versionId: string;
        /**
         * Original creation ID
         */
        createdId: string;
        /**
         * Creation timestamp
         */
        createdAt: string;
        /**
         * Last update timestamp
         */
        updatedAt: string;
        /**
         * Publication timestamp
         */
        publishedAt: string;
        /**
         * Whether the row is read-only
         */
        readonly: boolean;
        data: DemoRpgDataDialogs;
      };
    }>;
    pageInfo: {
      startCursor: string | null;
      endCursor: string | null;
      hasNextPage: boolean;
      hasPreviousPage: boolean;
    };
    totalCount: number;
  };
};

export type ListDialogsResponse = ListDialogsResponses[keyof ListDialogsResponses];

export type GetDialogsData = {
  body?: never;
  path: {
    /**
     * Row ID
     */
    rowId: string;
  };
  query?: never;
  url: '/tables/dialogs/row/{rowId}';
};

export type GetDialogsErrors = {
  /**
   * Unauthorized - invalid or missing access token or API key
   */
  401: unknown;
  /**
   * Not found
   */
  404: unknown;
};

export type GetDialogsResponses = {
  /**
   * Successful response
   */
  200: {
    /**
     * Row ID
     */
    id: string;
    /**
     * Current version ID
     */
    versionId: string;
    /**
     * Original creation ID
     */
    createdId: string;
    /**
     * Creation timestamp
     */
    createdAt: string;
    /**
     * Last update timestamp
     */
    updatedAt: string;
    /**
     * Publication timestamp
     */
    publishedAt: string;
    /**
     * Whether the row is read-only
     */
    readonly: boolean;
    data: DemoRpgDataDialogs;
  };
};

export type GetDialogsResponse = GetDialogsResponses[keyof GetDialogsResponses];

export type ListEffectsData = {
  /**
   * Query parameters for filtering and pagination
   */
  body: {
    /**
     * Number of items to return
     */
    first: number;
    /**
     * Cursor for pagination
     */
    after?: string;
    /**
     * Array of sorting criteria
     */
    orderBy?: Array<DemoRpgDataOrderBy>;
    /**
     * Filter conditions
     */
    where?: DemoRpgDataRowWhereInput;
  };
  path?: never;
  query?: never;
  url: '/tables/effects/rows';
};

export type ListEffectsErrors = {
  /**
   * Unauthorized - invalid or missing access token or API key
   */
  401: unknown;
};

export type ListEffectsResponses = {
  /**
   * Paginated list of rows
   */
  200: {
    edges: Array<{
      cursor: string;
      node: {
        /**
         * Row ID
         */
        id: string;
        /**
         * Current version ID
         */
        versionId: string;
        /**
         * Original creation ID
         */
        createdId: string;
        /**
         * Creation timestamp
         */
        createdAt: string;
        /**
         * Last update timestamp
         */
        updatedAt: string;
        /**
         * Publication timestamp
         */
        publishedAt: string;
        /**
         * Whether the row is read-only
         */
        readonly: boolean;
        data: DemoRpgDataEffects;
      };
    }>;
    pageInfo: {
      startCursor: string | null;
      endCursor: string | null;
      hasNextPage: boolean;
      hasPreviousPage: boolean;
    };
    totalCount: number;
  };
};

export type ListEffectsResponse = ListEffectsResponses[keyof ListEffectsResponses];

export type GetEffectsData = {
  body?: never;
  path: {
    /**
     * Row ID
     */
    rowId: string;
  };
  query?: never;
  url: '/tables/effects/row/{rowId}';
};

export type GetEffectsErrors = {
  /**
   * Unauthorized - invalid or missing access token or API key
   */
  401: unknown;
  /**
   * Not found
   */
  404: unknown;
};

export type GetEffectsResponses = {
  /**
   * Successful response
   */
  200: {
    /**
     * Row ID
     */
    id: string;
    /**
     * Current version ID
     */
    versionId: string;
    /**
     * Original creation ID
     */
    createdId: string;
    /**
     * Creation timestamp
     */
    createdAt: string;
    /**
     * Last update timestamp
     */
    updatedAt: string;
    /**
     * Publication timestamp
     */
    publishedAt: string;
    /**
     * Whether the row is read-only
     */
    readonly: boolean;
    data: DemoRpgDataEffects;
  };
};

export type GetEffectsResponse = GetEffectsResponses[keyof GetEffectsResponses];

export type GetEffectsForeignKeysByAbilitiesData = {
  body?: never;
  path: {
    /**
     * Row ID
     */
    rowId: string;
  };
  query: {
    /**
     * Number of items to return
     */
    first: number;
    /**
     * Cursor for pagination
     */
    after?: string;
  };
  url: '/tables/effects/row/{rowId}/foreign-keys-by/abilities';
};

export type GetEffectsForeignKeysByAbilitiesErrors = {
  /**
   * Unauthorized - invalid or missing access token or API key
   */
  401: unknown;
  /**
   * Not found
   */
  404: unknown;
};

export type GetEffectsForeignKeysByAbilitiesResponses = {
  /**
   * Paginated list of related rows
   */
  200: {
    edges: Array<{
      cursor: string;
      node: {
        /**
         * Row ID
         */
        id: string;
        /**
         * Current version ID
         */
        versionId: string;
        /**
         * Original creation ID
         */
        createdId: string;
        /**
         * Creation timestamp
         */
        createdAt: string;
        /**
         * Last update timestamp
         */
        updatedAt: string;
        /**
         * Publication timestamp
         */
        publishedAt: string;
        /**
         * Whether the row is read-only
         */
        readonly: boolean;
        data: DemoRpgDataAbilities;
      };
    }>;
    pageInfo: {
      startCursor: string | null;
      endCursor: string | null;
      hasNextPage: boolean;
      hasPreviousPage: boolean;
    };
    totalCount: number;
  };
};

export type GetEffectsForeignKeysByAbilitiesResponse =
  GetEffectsForeignKeysByAbilitiesResponses[keyof GetEffectsForeignKeysByAbilitiesResponses];

export type ListFactionsData = {
  /**
   * Query parameters for filtering and pagination
   */
  body: {
    /**
     * Number of items to return
     */
    first: number;
    /**
     * Cursor for pagination
     */
    after?: string;
    /**
     * Array of sorting criteria
     */
    orderBy?: Array<DemoRpgDataOrderBy>;
    /**
     * Filter conditions
     */
    where?: DemoRpgDataRowWhereInput;
  };
  path?: never;
  query?: never;
  url: '/tables/factions/rows';
};

export type ListFactionsErrors = {
  /**
   * Unauthorized - invalid or missing access token or API key
   */
  401: unknown;
};

export type ListFactionsResponses = {
  /**
   * Paginated list of rows
   */
  200: {
    edges: Array<{
      cursor: string;
      node: {
        /**
         * Row ID
         */
        id: string;
        /**
         * Current version ID
         */
        versionId: string;
        /**
         * Original creation ID
         */
        createdId: string;
        /**
         * Creation timestamp
         */
        createdAt: string;
        /**
         * Last update timestamp
         */
        updatedAt: string;
        /**
         * Publication timestamp
         */
        publishedAt: string;
        /**
         * Whether the row is read-only
         */
        readonly: boolean;
        data: DemoRpgDataFactions;
      };
    }>;
    pageInfo: {
      startCursor: string | null;
      endCursor: string | null;
      hasNextPage: boolean;
      hasPreviousPage: boolean;
    };
    totalCount: number;
  };
};

export type ListFactionsResponse = ListFactionsResponses[keyof ListFactionsResponses];

export type GetFactionsData = {
  body?: never;
  path: {
    /**
     * Row ID
     */
    rowId: string;
  };
  query?: never;
  url: '/tables/factions/row/{rowId}';
};

export type GetFactionsErrors = {
  /**
   * Unauthorized - invalid or missing access token or API key
   */
  401: unknown;
  /**
   * Not found
   */
  404: unknown;
};

export type GetFactionsResponses = {
  /**
   * Successful response
   */
  200: {
    /**
     * Row ID
     */
    id: string;
    /**
     * Current version ID
     */
    versionId: string;
    /**
     * Original creation ID
     */
    createdId: string;
    /**
     * Creation timestamp
     */
    createdAt: string;
    /**
     * Last update timestamp
     */
    updatedAt: string;
    /**
     * Publication timestamp
     */
    publishedAt: string;
    /**
     * Whether the row is read-only
     */
    readonly: boolean;
    data: DemoRpgDataFactions;
  };
};

export type GetFactionsResponse = GetFactionsResponses[keyof GetFactionsResponses];

export type GetFactionsForeignKeysByMonstersData = {
  body?: never;
  path: {
    /**
     * Row ID
     */
    rowId: string;
  };
  query: {
    /**
     * Number of items to return
     */
    first: number;
    /**
     * Cursor for pagination
     */
    after?: string;
  };
  url: '/tables/factions/row/{rowId}/foreign-keys-by/monsters';
};

export type GetFactionsForeignKeysByMonstersErrors = {
  /**
   * Unauthorized - invalid or missing access token or API key
   */
  401: unknown;
  /**
   * Not found
   */
  404: unknown;
};

export type GetFactionsForeignKeysByMonstersResponses = {
  /**
   * Paginated list of related rows
   */
  200: {
    edges: Array<{
      cursor: string;
      node: {
        /**
         * Row ID
         */
        id: string;
        /**
         * Current version ID
         */
        versionId: string;
        /**
         * Original creation ID
         */
        createdId: string;
        /**
         * Creation timestamp
         */
        createdAt: string;
        /**
         * Last update timestamp
         */
        updatedAt: string;
        /**
         * Publication timestamp
         */
        publishedAt: string;
        /**
         * Whether the row is read-only
         */
        readonly: boolean;
        data: DemoRpgDataMonsters;
      };
    }>;
    pageInfo: {
      startCursor: string | null;
      endCursor: string | null;
      hasNextPage: boolean;
      hasPreviousPage: boolean;
    };
    totalCount: number;
  };
};

export type GetFactionsForeignKeysByMonstersResponse =
  GetFactionsForeignKeysByMonstersResponses[keyof GetFactionsForeignKeysByMonstersResponses];

export type GetFactionsForeignKeysByNpcsData = {
  body?: never;
  path: {
    /**
     * Row ID
     */
    rowId: string;
  };
  query: {
    /**
     * Number of items to return
     */
    first: number;
    /**
     * Cursor for pagination
     */
    after?: string;
  };
  url: '/tables/factions/row/{rowId}/foreign-keys-by/npcs';
};

export type GetFactionsForeignKeysByNpcsErrors = {
  /**
   * Unauthorized - invalid or missing access token or API key
   */
  401: unknown;
  /**
   * Not found
   */
  404: unknown;
};

export type GetFactionsForeignKeysByNpcsResponses = {
  /**
   * Paginated list of related rows
   */
  200: {
    edges: Array<{
      cursor: string;
      node: {
        /**
         * Row ID
         */
        id: string;
        /**
         * Current version ID
         */
        versionId: string;
        /**
         * Original creation ID
         */
        createdId: string;
        /**
         * Creation timestamp
         */
        createdAt: string;
        /**
         * Last update timestamp
         */
        updatedAt: string;
        /**
         * Publication timestamp
         */
        publishedAt: string;
        /**
         * Whether the row is read-only
         */
        readonly: boolean;
        data: DemoRpgDataNpcs;
      };
    }>;
    pageInfo: {
      startCursor: string | null;
      endCursor: string | null;
      hasNextPage: boolean;
      hasPreviousPage: boolean;
    };
    totalCount: number;
  };
};

export type GetFactionsForeignKeysByNpcsResponse =
  GetFactionsForeignKeysByNpcsResponses[keyof GetFactionsForeignKeysByNpcsResponses];

export type ListHeroesData = {
  /**
   * Query parameters for filtering and pagination
   */
  body: {
    /**
     * Number of items to return
     */
    first: number;
    /**
     * Cursor for pagination
     */
    after?: string;
    /**
     * Array of sorting criteria
     */
    orderBy?: Array<DemoRpgDataOrderBy>;
    /**
     * Filter conditions
     */
    where?: DemoRpgDataRowWhereInput;
  };
  path?: never;
  query?: never;
  url: '/tables/heroes/rows';
};

export type ListHeroesErrors = {
  /**
   * Unauthorized - invalid or missing access token or API key
   */
  401: unknown;
};

export type ListHeroesResponses = {
  /**
   * Paginated list of rows
   */
  200: {
    edges: Array<{
      cursor: string;
      node: {
        /**
         * Row ID
         */
        id: string;
        /**
         * Current version ID
         */
        versionId: string;
        /**
         * Original creation ID
         */
        createdId: string;
        /**
         * Creation timestamp
         */
        createdAt: string;
        /**
         * Last update timestamp
         */
        updatedAt: string;
        /**
         * Publication timestamp
         */
        publishedAt: string;
        /**
         * Whether the row is read-only
         */
        readonly: boolean;
        data: DemoRpgDataHeroes;
      };
    }>;
    pageInfo: {
      startCursor: string | null;
      endCursor: string | null;
      hasNextPage: boolean;
      hasPreviousPage: boolean;
    };
    totalCount: number;
  };
};

export type ListHeroesResponse = ListHeroesResponses[keyof ListHeroesResponses];

export type GetHeroesData = {
  body?: never;
  path: {
    /**
     * Row ID
     */
    rowId: string;
  };
  query?: never;
  url: '/tables/heroes/row/{rowId}';
};

export type GetHeroesErrors = {
  /**
   * Unauthorized - invalid or missing access token or API key
   */
  401: unknown;
  /**
   * Not found
   */
  404: unknown;
};

export type GetHeroesResponses = {
  /**
   * Successful response
   */
  200: {
    /**
     * Row ID
     */
    id: string;
    /**
     * Current version ID
     */
    versionId: string;
    /**
     * Original creation ID
     */
    createdId: string;
    /**
     * Creation timestamp
     */
    createdAt: string;
    /**
     * Last update timestamp
     */
    updatedAt: string;
    /**
     * Publication timestamp
     */
    publishedAt: string;
    /**
     * Whether the row is read-only
     */
    readonly: boolean;
    data: DemoRpgDataHeroes;
  };
};

export type GetHeroesResponse = GetHeroesResponses[keyof GetHeroesResponses];

export type GetHeroesForeignKeysByPartiesData = {
  body?: never;
  path: {
    /**
     * Row ID
     */
    rowId: string;
  };
  query: {
    /**
     * Number of items to return
     */
    first: number;
    /**
     * Cursor for pagination
     */
    after?: string;
  };
  url: '/tables/heroes/row/{rowId}/foreign-keys-by/parties';
};

export type GetHeroesForeignKeysByPartiesErrors = {
  /**
   * Unauthorized - invalid or missing access token or API key
   */
  401: unknown;
  /**
   * Not found
   */
  404: unknown;
};

export type GetHeroesForeignKeysByPartiesResponses = {
  /**
   * Paginated list of related rows
   */
  200: {
    edges: Array<{
      cursor: string;
      node: {
        /**
         * Row ID
         */
        id: string;
        /**
         * Current version ID
         */
        versionId: string;
        /**
         * Original creation ID
         */
        createdId: string;
        /**
         * Creation timestamp
         */
        createdAt: string;
        /**
         * Last update timestamp
         */
        updatedAt: string;
        /**
         * Publication timestamp
         */
        publishedAt: string;
        /**
         * Whether the row is read-only
         */
        readonly: boolean;
        data: DemoRpgDataParties;
      };
    }>;
    pageInfo: {
      startCursor: string | null;
      endCursor: string | null;
      hasNextPage: boolean;
      hasPreviousPage: boolean;
    };
    totalCount: number;
  };
};

export type GetHeroesForeignKeysByPartiesResponse =
  GetHeroesForeignKeysByPartiesResponses[keyof GetHeroesForeignKeysByPartiesResponses];

export type ListItemTypesData = {
  /**
   * Query parameters for filtering and pagination
   */
  body: {
    /**
     * Number of items to return
     */
    first: number;
    /**
     * Cursor for pagination
     */
    after?: string;
    /**
     * Array of sorting criteria
     */
    orderBy?: Array<DemoRpgDataOrderBy>;
    /**
     * Filter conditions
     */
    where?: DemoRpgDataRowWhereInput;
  };
  path?: never;
  query?: never;
  url: '/tables/item_types/rows';
};

export type ListItemTypesErrors = {
  /**
   * Unauthorized - invalid or missing access token or API key
   */
  401: unknown;
};

export type ListItemTypesResponses = {
  /**
   * Paginated list of rows
   */
  200: {
    edges: Array<{
      cursor: string;
      node: {
        /**
         * Row ID
         */
        id: string;
        /**
         * Current version ID
         */
        versionId: string;
        /**
         * Original creation ID
         */
        createdId: string;
        /**
         * Creation timestamp
         */
        createdAt: string;
        /**
         * Last update timestamp
         */
        updatedAt: string;
        /**
         * Publication timestamp
         */
        publishedAt: string;
        /**
         * Whether the row is read-only
         */
        readonly: boolean;
        data: DemoRpgDataItemTypes;
      };
    }>;
    pageInfo: {
      startCursor: string | null;
      endCursor: string | null;
      hasNextPage: boolean;
      hasPreviousPage: boolean;
    };
    totalCount: number;
  };
};

export type ListItemTypesResponse = ListItemTypesResponses[keyof ListItemTypesResponses];

export type GetItemTypesData = {
  body?: never;
  path: {
    /**
     * Row ID
     */
    rowId: string;
  };
  query?: never;
  url: '/tables/item_types/row/{rowId}';
};

export type GetItemTypesErrors = {
  /**
   * Unauthorized - invalid or missing access token or API key
   */
  401: unknown;
  /**
   * Not found
   */
  404: unknown;
};

export type GetItemTypesResponses = {
  /**
   * Successful response
   */
  200: {
    /**
     * Row ID
     */
    id: string;
    /**
     * Current version ID
     */
    versionId: string;
    /**
     * Original creation ID
     */
    createdId: string;
    /**
     * Creation timestamp
     */
    createdAt: string;
    /**
     * Last update timestamp
     */
    updatedAt: string;
    /**
     * Publication timestamp
     */
    publishedAt: string;
    /**
     * Whether the row is read-only
     */
    readonly: boolean;
    data: DemoRpgDataItemTypes;
  };
};

export type GetItemTypesResponse = GetItemTypesResponses[keyof GetItemTypesResponses];

export type GetItemTypesForeignKeysByItemsData = {
  body?: never;
  path: {
    /**
     * Row ID
     */
    rowId: string;
  };
  query: {
    /**
     * Number of items to return
     */
    first: number;
    /**
     * Cursor for pagination
     */
    after?: string;
  };
  url: '/tables/item_types/row/{rowId}/foreign-keys-by/items';
};

export type GetItemTypesForeignKeysByItemsErrors = {
  /**
   * Unauthorized - invalid or missing access token or API key
   */
  401: unknown;
  /**
   * Not found
   */
  404: unknown;
};

export type GetItemTypesForeignKeysByItemsResponses = {
  /**
   * Paginated list of related rows
   */
  200: {
    edges: Array<{
      cursor: string;
      node: {
        /**
         * Row ID
         */
        id: string;
        /**
         * Current version ID
         */
        versionId: string;
        /**
         * Original creation ID
         */
        createdId: string;
        /**
         * Creation timestamp
         */
        createdAt: string;
        /**
         * Last update timestamp
         */
        updatedAt: string;
        /**
         * Publication timestamp
         */
        publishedAt: string;
        /**
         * Whether the row is read-only
         */
        readonly: boolean;
        data: DemoRpgDataItems;
      };
    }>;
    pageInfo: {
      startCursor: string | null;
      endCursor: string | null;
      hasNextPage: boolean;
      hasPreviousPage: boolean;
    };
    totalCount: number;
  };
};

export type GetItemTypesForeignKeysByItemsResponse =
  GetItemTypesForeignKeysByItemsResponses[keyof GetItemTypesForeignKeysByItemsResponses];

export type ListItemsData = {
  /**
   * Query parameters for filtering and pagination
   */
  body: {
    /**
     * Number of items to return
     */
    first: number;
    /**
     * Cursor for pagination
     */
    after?: string;
    /**
     * Array of sorting criteria
     */
    orderBy?: Array<DemoRpgDataOrderBy>;
    /**
     * Filter conditions
     */
    where?: DemoRpgDataRowWhereInput;
  };
  path?: never;
  query?: never;
  url: '/tables/items/rows';
};

export type ListItemsErrors = {
  /**
   * Unauthorized - invalid or missing access token or API key
   */
  401: unknown;
};

export type ListItemsResponses = {
  /**
   * Paginated list of rows
   */
  200: {
    edges: Array<{
      cursor: string;
      node: {
        /**
         * Row ID
         */
        id: string;
        /**
         * Current version ID
         */
        versionId: string;
        /**
         * Original creation ID
         */
        createdId: string;
        /**
         * Creation timestamp
         */
        createdAt: string;
        /**
         * Last update timestamp
         */
        updatedAt: string;
        /**
         * Publication timestamp
         */
        publishedAt: string;
        /**
         * Whether the row is read-only
         */
        readonly: boolean;
        data: DemoRpgDataItems;
      };
    }>;
    pageInfo: {
      startCursor: string | null;
      endCursor: string | null;
      hasNextPage: boolean;
      hasPreviousPage: boolean;
    };
    totalCount: number;
  };
};

export type ListItemsResponse = ListItemsResponses[keyof ListItemsResponses];

export type GetItemsData = {
  body?: never;
  path: {
    /**
     * Row ID
     */
    rowId: string;
  };
  query?: never;
  url: '/tables/items/row/{rowId}';
};

export type GetItemsErrors = {
  /**
   * Unauthorized - invalid or missing access token or API key
   */
  401: unknown;
  /**
   * Not found
   */
  404: unknown;
};

export type GetItemsResponses = {
  /**
   * Successful response
   */
  200: {
    /**
     * Row ID
     */
    id: string;
    /**
     * Current version ID
     */
    versionId: string;
    /**
     * Original creation ID
     */
    createdId: string;
    /**
     * Creation timestamp
     */
    createdAt: string;
    /**
     * Last update timestamp
     */
    updatedAt: string;
    /**
     * Publication timestamp
     */
    publishedAt: string;
    /**
     * Whether the row is read-only
     */
    readonly: boolean;
    data: DemoRpgDataItems;
  };
};

export type GetItemsResponse = GetItemsResponses[keyof GetItemsResponses];

export type GetItemsForeignKeysByHeroesData = {
  body?: never;
  path: {
    /**
     * Row ID
     */
    rowId: string;
  };
  query: {
    /**
     * Number of items to return
     */
    first: number;
    /**
     * Cursor for pagination
     */
    after?: string;
  };
  url: '/tables/items/row/{rowId}/foreign-keys-by/heroes';
};

export type GetItemsForeignKeysByHeroesErrors = {
  /**
   * Unauthorized - invalid or missing access token or API key
   */
  401: unknown;
  /**
   * Not found
   */
  404: unknown;
};

export type GetItemsForeignKeysByHeroesResponses = {
  /**
   * Paginated list of related rows
   */
  200: {
    edges: Array<{
      cursor: string;
      node: {
        /**
         * Row ID
         */
        id: string;
        /**
         * Current version ID
         */
        versionId: string;
        /**
         * Original creation ID
         */
        createdId: string;
        /**
         * Creation timestamp
         */
        createdAt: string;
        /**
         * Last update timestamp
         */
        updatedAt: string;
        /**
         * Publication timestamp
         */
        publishedAt: string;
        /**
         * Whether the row is read-only
         */
        readonly: boolean;
        data: DemoRpgDataHeroes;
      };
    }>;
    pageInfo: {
      startCursor: string | null;
      endCursor: string | null;
      hasNextPage: boolean;
      hasPreviousPage: boolean;
    };
    totalCount: number;
  };
};

export type GetItemsForeignKeysByHeroesResponse =
  GetItemsForeignKeysByHeroesResponses[keyof GetItemsForeignKeysByHeroesResponses];

export type GetItemsForeignKeysByMonstersData = {
  body?: never;
  path: {
    /**
     * Row ID
     */
    rowId: string;
  };
  query: {
    /**
     * Number of items to return
     */
    first: number;
    /**
     * Cursor for pagination
     */
    after?: string;
  };
  url: '/tables/items/row/{rowId}/foreign-keys-by/monsters';
};

export type GetItemsForeignKeysByMonstersErrors = {
  /**
   * Unauthorized - invalid or missing access token or API key
   */
  401: unknown;
  /**
   * Not found
   */
  404: unknown;
};

export type GetItemsForeignKeysByMonstersResponses = {
  /**
   * Paginated list of related rows
   */
  200: {
    edges: Array<{
      cursor: string;
      node: {
        /**
         * Row ID
         */
        id: string;
        /**
         * Current version ID
         */
        versionId: string;
        /**
         * Original creation ID
         */
        createdId: string;
        /**
         * Creation timestamp
         */
        createdAt: string;
        /**
         * Last update timestamp
         */
        updatedAt: string;
        /**
         * Publication timestamp
         */
        publishedAt: string;
        /**
         * Whether the row is read-only
         */
        readonly: boolean;
        data: DemoRpgDataMonsters;
      };
    }>;
    pageInfo: {
      startCursor: string | null;
      endCursor: string | null;
      hasNextPage: boolean;
      hasPreviousPage: boolean;
    };
    totalCount: number;
  };
};

export type GetItemsForeignKeysByMonstersResponse =
  GetItemsForeignKeysByMonstersResponses[keyof GetItemsForeignKeysByMonstersResponses];

export type GetItemsForeignKeysByNpcsData = {
  body?: never;
  path: {
    /**
     * Row ID
     */
    rowId: string;
  };
  query: {
    /**
     * Number of items to return
     */
    first: number;
    /**
     * Cursor for pagination
     */
    after?: string;
  };
  url: '/tables/items/row/{rowId}/foreign-keys-by/npcs';
};

export type GetItemsForeignKeysByNpcsErrors = {
  /**
   * Unauthorized - invalid or missing access token or API key
   */
  401: unknown;
  /**
   * Not found
   */
  404: unknown;
};

export type GetItemsForeignKeysByNpcsResponses = {
  /**
   * Paginated list of related rows
   */
  200: {
    edges: Array<{
      cursor: string;
      node: {
        /**
         * Row ID
         */
        id: string;
        /**
         * Current version ID
         */
        versionId: string;
        /**
         * Original creation ID
         */
        createdId: string;
        /**
         * Creation timestamp
         */
        createdAt: string;
        /**
         * Last update timestamp
         */
        updatedAt: string;
        /**
         * Publication timestamp
         */
        publishedAt: string;
        /**
         * Whether the row is read-only
         */
        readonly: boolean;
        data: DemoRpgDataNpcs;
      };
    }>;
    pageInfo: {
      startCursor: string | null;
      endCursor: string | null;
      hasNextPage: boolean;
      hasPreviousPage: boolean;
    };
    totalCount: number;
  };
};

export type GetItemsForeignKeysByNpcsResponse =
  GetItemsForeignKeysByNpcsResponses[keyof GetItemsForeignKeysByNpcsResponses];

export type GetItemsForeignKeysByQuestsData = {
  body?: never;
  path: {
    /**
     * Row ID
     */
    rowId: string;
  };
  query: {
    /**
     * Number of items to return
     */
    first: number;
    /**
     * Cursor for pagination
     */
    after?: string;
  };
  url: '/tables/items/row/{rowId}/foreign-keys-by/quests';
};

export type GetItemsForeignKeysByQuestsErrors = {
  /**
   * Unauthorized - invalid or missing access token or API key
   */
  401: unknown;
  /**
   * Not found
   */
  404: unknown;
};

export type GetItemsForeignKeysByQuestsResponses = {
  /**
   * Paginated list of related rows
   */
  200: {
    edges: Array<{
      cursor: string;
      node: {
        /**
         * Row ID
         */
        id: string;
        /**
         * Current version ID
         */
        versionId: string;
        /**
         * Original creation ID
         */
        createdId: string;
        /**
         * Creation timestamp
         */
        createdAt: string;
        /**
         * Last update timestamp
         */
        updatedAt: string;
        /**
         * Publication timestamp
         */
        publishedAt: string;
        /**
         * Whether the row is read-only
         */
        readonly: boolean;
        data: DemoRpgDataQuests;
      };
    }>;
    pageInfo: {
      startCursor: string | null;
      endCursor: string | null;
      hasNextPage: boolean;
      hasPreviousPage: boolean;
    };
    totalCount: number;
  };
};

export type GetItemsForeignKeysByQuestsResponse =
  GetItemsForeignKeysByQuestsResponses[keyof GetItemsForeignKeysByQuestsResponses];

export type ListLocationsData = {
  /**
   * Query parameters for filtering and pagination
   */
  body: {
    /**
     * Number of items to return
     */
    first: number;
    /**
     * Cursor for pagination
     */
    after?: string;
    /**
     * Array of sorting criteria
     */
    orderBy?: Array<DemoRpgDataOrderBy>;
    /**
     * Filter conditions
     */
    where?: DemoRpgDataRowWhereInput;
  };
  path?: never;
  query?: never;
  url: '/tables/locations/rows';
};

export type ListLocationsErrors = {
  /**
   * Unauthorized - invalid or missing access token or API key
   */
  401: unknown;
};

export type ListLocationsResponses = {
  /**
   * Paginated list of rows
   */
  200: {
    edges: Array<{
      cursor: string;
      node: {
        /**
         * Row ID
         */
        id: string;
        /**
         * Current version ID
         */
        versionId: string;
        /**
         * Original creation ID
         */
        createdId: string;
        /**
         * Creation timestamp
         */
        createdAt: string;
        /**
         * Last update timestamp
         */
        updatedAt: string;
        /**
         * Publication timestamp
         */
        publishedAt: string;
        /**
         * Whether the row is read-only
         */
        readonly: boolean;
        data: DemoRpgDataLocations;
      };
    }>;
    pageInfo: {
      startCursor: string | null;
      endCursor: string | null;
      hasNextPage: boolean;
      hasPreviousPage: boolean;
    };
    totalCount: number;
  };
};

export type ListLocationsResponse = ListLocationsResponses[keyof ListLocationsResponses];

export type GetLocationsData = {
  body?: never;
  path: {
    /**
     * Row ID
     */
    rowId: string;
  };
  query?: never;
  url: '/tables/locations/row/{rowId}';
};

export type GetLocationsErrors = {
  /**
   * Unauthorized - invalid or missing access token or API key
   */
  401: unknown;
  /**
   * Not found
   */
  404: unknown;
};

export type GetLocationsResponses = {
  /**
   * Successful response
   */
  200: {
    /**
     * Row ID
     */
    id: string;
    /**
     * Current version ID
     */
    versionId: string;
    /**
     * Original creation ID
     */
    createdId: string;
    /**
     * Creation timestamp
     */
    createdAt: string;
    /**
     * Last update timestamp
     */
    updatedAt: string;
    /**
     * Publication timestamp
     */
    publishedAt: string;
    /**
     * Whether the row is read-only
     */
    readonly: boolean;
    data: DemoRpgDataLocations;
  };
};

export type GetLocationsResponse = GetLocationsResponses[keyof GetLocationsResponses];

export type GetLocationsForeignKeysByNpcsData = {
  body?: never;
  path: {
    /**
     * Row ID
     */
    rowId: string;
  };
  query: {
    /**
     * Number of items to return
     */
    first: number;
    /**
     * Cursor for pagination
     */
    after?: string;
  };
  url: '/tables/locations/row/{rowId}/foreign-keys-by/npcs';
};

export type GetLocationsForeignKeysByNpcsErrors = {
  /**
   * Unauthorized - invalid or missing access token or API key
   */
  401: unknown;
  /**
   * Not found
   */
  404: unknown;
};

export type GetLocationsForeignKeysByNpcsResponses = {
  /**
   * Paginated list of related rows
   */
  200: {
    edges: Array<{
      cursor: string;
      node: {
        /**
         * Row ID
         */
        id: string;
        /**
         * Current version ID
         */
        versionId: string;
        /**
         * Original creation ID
         */
        createdId: string;
        /**
         * Creation timestamp
         */
        createdAt: string;
        /**
         * Last update timestamp
         */
        updatedAt: string;
        /**
         * Publication timestamp
         */
        publishedAt: string;
        /**
         * Whether the row is read-only
         */
        readonly: boolean;
        data: DemoRpgDataNpcs;
      };
    }>;
    pageInfo: {
      startCursor: string | null;
      endCursor: string | null;
      hasNextPage: boolean;
      hasPreviousPage: boolean;
    };
    totalCount: number;
  };
};

export type GetLocationsForeignKeysByNpcsResponse =
  GetLocationsForeignKeysByNpcsResponses[keyof GetLocationsForeignKeysByNpcsResponses];

export type GetLocationsForeignKeysByQuestsData = {
  body?: never;
  path: {
    /**
     * Row ID
     */
    rowId: string;
  };
  query: {
    /**
     * Number of items to return
     */
    first: number;
    /**
     * Cursor for pagination
     */
    after?: string;
  };
  url: '/tables/locations/row/{rowId}/foreign-keys-by/quests';
};

export type GetLocationsForeignKeysByQuestsErrors = {
  /**
   * Unauthorized - invalid or missing access token or API key
   */
  401: unknown;
  /**
   * Not found
   */
  404: unknown;
};

export type GetLocationsForeignKeysByQuestsResponses = {
  /**
   * Paginated list of related rows
   */
  200: {
    edges: Array<{
      cursor: string;
      node: {
        /**
         * Row ID
         */
        id: string;
        /**
         * Current version ID
         */
        versionId: string;
        /**
         * Original creation ID
         */
        createdId: string;
        /**
         * Creation timestamp
         */
        createdAt: string;
        /**
         * Last update timestamp
         */
        updatedAt: string;
        /**
         * Publication timestamp
         */
        publishedAt: string;
        /**
         * Whether the row is read-only
         */
        readonly: boolean;
        data: DemoRpgDataQuests;
      };
    }>;
    pageInfo: {
      startCursor: string | null;
      endCursor: string | null;
      hasNextPage: boolean;
      hasPreviousPage: boolean;
    };
    totalCount: number;
  };
};

export type GetLocationsForeignKeysByQuestsResponse =
  GetLocationsForeignKeysByQuestsResponses[keyof GetLocationsForeignKeysByQuestsResponses];

export type ListMonstersData = {
  /**
   * Query parameters for filtering and pagination
   */
  body: {
    /**
     * Number of items to return
     */
    first: number;
    /**
     * Cursor for pagination
     */
    after?: string;
    /**
     * Array of sorting criteria
     */
    orderBy?: Array<DemoRpgDataOrderBy>;
    /**
     * Filter conditions
     */
    where?: DemoRpgDataRowWhereInput;
  };
  path?: never;
  query?: never;
  url: '/tables/monsters/rows';
};

export type ListMonstersErrors = {
  /**
   * Unauthorized - invalid or missing access token or API key
   */
  401: unknown;
};

export type ListMonstersResponses = {
  /**
   * Paginated list of rows
   */
  200: {
    edges: Array<{
      cursor: string;
      node: {
        /**
         * Row ID
         */
        id: string;
        /**
         * Current version ID
         */
        versionId: string;
        /**
         * Original creation ID
         */
        createdId: string;
        /**
         * Creation timestamp
         */
        createdAt: string;
        /**
         * Last update timestamp
         */
        updatedAt: string;
        /**
         * Publication timestamp
         */
        publishedAt: string;
        /**
         * Whether the row is read-only
         */
        readonly: boolean;
        data: DemoRpgDataMonsters;
      };
    }>;
    pageInfo: {
      startCursor: string | null;
      endCursor: string | null;
      hasNextPage: boolean;
      hasPreviousPage: boolean;
    };
    totalCount: number;
  };
};

export type ListMonstersResponse = ListMonstersResponses[keyof ListMonstersResponses];

export type GetMonstersData = {
  body?: never;
  path: {
    /**
     * Row ID
     */
    rowId: string;
  };
  query?: never;
  url: '/tables/monsters/row/{rowId}';
};

export type GetMonstersErrors = {
  /**
   * Unauthorized - invalid or missing access token or API key
   */
  401: unknown;
  /**
   * Not found
   */
  404: unknown;
};

export type GetMonstersResponses = {
  /**
   * Successful response
   */
  200: {
    /**
     * Row ID
     */
    id: string;
    /**
     * Current version ID
     */
    versionId: string;
    /**
     * Original creation ID
     */
    createdId: string;
    /**
     * Creation timestamp
     */
    createdAt: string;
    /**
     * Last update timestamp
     */
    updatedAt: string;
    /**
     * Publication timestamp
     */
    publishedAt: string;
    /**
     * Whether the row is read-only
     */
    readonly: boolean;
    data: DemoRpgDataMonsters;
  };
};

export type GetMonstersResponse = GetMonstersResponses[keyof GetMonstersResponses];

export type ListNpcsData = {
  /**
   * Query parameters for filtering and pagination
   */
  body: {
    /**
     * Number of items to return
     */
    first: number;
    /**
     * Cursor for pagination
     */
    after?: string;
    /**
     * Array of sorting criteria
     */
    orderBy?: Array<DemoRpgDataOrderBy>;
    /**
     * Filter conditions
     */
    where?: DemoRpgDataRowWhereInput;
  };
  path?: never;
  query?: never;
  url: '/tables/npcs/rows';
};

export type ListNpcsErrors = {
  /**
   * Unauthorized - invalid or missing access token or API key
   */
  401: unknown;
};

export type ListNpcsResponses = {
  /**
   * Paginated list of rows
   */
  200: {
    edges: Array<{
      cursor: string;
      node: {
        /**
         * Row ID
         */
        id: string;
        /**
         * Current version ID
         */
        versionId: string;
        /**
         * Original creation ID
         */
        createdId: string;
        /**
         * Creation timestamp
         */
        createdAt: string;
        /**
         * Last update timestamp
         */
        updatedAt: string;
        /**
         * Publication timestamp
         */
        publishedAt: string;
        /**
         * Whether the row is read-only
         */
        readonly: boolean;
        data: DemoRpgDataNpcs;
      };
    }>;
    pageInfo: {
      startCursor: string | null;
      endCursor: string | null;
      hasNextPage: boolean;
      hasPreviousPage: boolean;
    };
    totalCount: number;
  };
};

export type ListNpcsResponse = ListNpcsResponses[keyof ListNpcsResponses];

export type GetNpcsData = {
  body?: never;
  path: {
    /**
     * Row ID
     */
    rowId: string;
  };
  query?: never;
  url: '/tables/npcs/row/{rowId}';
};

export type GetNpcsErrors = {
  /**
   * Unauthorized - invalid or missing access token or API key
   */
  401: unknown;
  /**
   * Not found
   */
  404: unknown;
};

export type GetNpcsResponses = {
  /**
   * Successful response
   */
  200: {
    /**
     * Row ID
     */
    id: string;
    /**
     * Current version ID
     */
    versionId: string;
    /**
     * Original creation ID
     */
    createdId: string;
    /**
     * Creation timestamp
     */
    createdAt: string;
    /**
     * Last update timestamp
     */
    updatedAt: string;
    /**
     * Publication timestamp
     */
    publishedAt: string;
    /**
     * Whether the row is read-only
     */
    readonly: boolean;
    data: DemoRpgDataNpcs;
  };
};

export type GetNpcsResponse = GetNpcsResponses[keyof GetNpcsResponses];

export type GetNpcsForeignKeysByDialogsData = {
  body?: never;
  path: {
    /**
     * Row ID
     */
    rowId: string;
  };
  query: {
    /**
     * Number of items to return
     */
    first: number;
    /**
     * Cursor for pagination
     */
    after?: string;
  };
  url: '/tables/npcs/row/{rowId}/foreign-keys-by/dialogs';
};

export type GetNpcsForeignKeysByDialogsErrors = {
  /**
   * Unauthorized - invalid or missing access token or API key
   */
  401: unknown;
  /**
   * Not found
   */
  404: unknown;
};

export type GetNpcsForeignKeysByDialogsResponses = {
  /**
   * Paginated list of related rows
   */
  200: {
    edges: Array<{
      cursor: string;
      node: {
        /**
         * Row ID
         */
        id: string;
        /**
         * Current version ID
         */
        versionId: string;
        /**
         * Original creation ID
         */
        createdId: string;
        /**
         * Creation timestamp
         */
        createdAt: string;
        /**
         * Last update timestamp
         */
        updatedAt: string;
        /**
         * Publication timestamp
         */
        publishedAt: string;
        /**
         * Whether the row is read-only
         */
        readonly: boolean;
        data: DemoRpgDataDialogs;
      };
    }>;
    pageInfo: {
      startCursor: string | null;
      endCursor: string | null;
      hasNextPage: boolean;
      hasPreviousPage: boolean;
    };
    totalCount: number;
  };
};

export type GetNpcsForeignKeysByDialogsResponse =
  GetNpcsForeignKeysByDialogsResponses[keyof GetNpcsForeignKeysByDialogsResponses];

export type GetNpcsForeignKeysByQuestsData = {
  body?: never;
  path: {
    /**
     * Row ID
     */
    rowId: string;
  };
  query: {
    /**
     * Number of items to return
     */
    first: number;
    /**
     * Cursor for pagination
     */
    after?: string;
  };
  url: '/tables/npcs/row/{rowId}/foreign-keys-by/quests';
};

export type GetNpcsForeignKeysByQuestsErrors = {
  /**
   * Unauthorized - invalid or missing access token or API key
   */
  401: unknown;
  /**
   * Not found
   */
  404: unknown;
};

export type GetNpcsForeignKeysByQuestsResponses = {
  /**
   * Paginated list of related rows
   */
  200: {
    edges: Array<{
      cursor: string;
      node: {
        /**
         * Row ID
         */
        id: string;
        /**
         * Current version ID
         */
        versionId: string;
        /**
         * Original creation ID
         */
        createdId: string;
        /**
         * Creation timestamp
         */
        createdAt: string;
        /**
         * Last update timestamp
         */
        updatedAt: string;
        /**
         * Publication timestamp
         */
        publishedAt: string;
        /**
         * Whether the row is read-only
         */
        readonly: boolean;
        data: DemoRpgDataQuests;
      };
    }>;
    pageInfo: {
      startCursor: string | null;
      endCursor: string | null;
      hasNextPage: boolean;
      hasPreviousPage: boolean;
    };
    totalCount: number;
  };
};

export type GetNpcsForeignKeysByQuestsResponse =
  GetNpcsForeignKeysByQuestsResponses[keyof GetNpcsForeignKeysByQuestsResponses];

export type ListPartiesData = {
  /**
   * Query parameters for filtering and pagination
   */
  body: {
    /**
     * Number of items to return
     */
    first: number;
    /**
     * Cursor for pagination
     */
    after?: string;
    /**
     * Array of sorting criteria
     */
    orderBy?: Array<DemoRpgDataOrderBy>;
    /**
     * Filter conditions
     */
    where?: DemoRpgDataRowWhereInput;
  };
  path?: never;
  query?: never;
  url: '/tables/parties/rows';
};

export type ListPartiesErrors = {
  /**
   * Unauthorized - invalid or missing access token or API key
   */
  401: unknown;
};

export type ListPartiesResponses = {
  /**
   * Paginated list of rows
   */
  200: {
    edges: Array<{
      cursor: string;
      node: {
        /**
         * Row ID
         */
        id: string;
        /**
         * Current version ID
         */
        versionId: string;
        /**
         * Original creation ID
         */
        createdId: string;
        /**
         * Creation timestamp
         */
        createdAt: string;
        /**
         * Last update timestamp
         */
        updatedAt: string;
        /**
         * Publication timestamp
         */
        publishedAt: string;
        /**
         * Whether the row is read-only
         */
        readonly: boolean;
        data: DemoRpgDataParties;
      };
    }>;
    pageInfo: {
      startCursor: string | null;
      endCursor: string | null;
      hasNextPage: boolean;
      hasPreviousPage: boolean;
    };
    totalCount: number;
  };
};

export type ListPartiesResponse = ListPartiesResponses[keyof ListPartiesResponses];

export type GetPartiesData = {
  body?: never;
  path: {
    /**
     * Row ID
     */
    rowId: string;
  };
  query?: never;
  url: '/tables/parties/row/{rowId}';
};

export type GetPartiesErrors = {
  /**
   * Unauthorized - invalid or missing access token or API key
   */
  401: unknown;
  /**
   * Not found
   */
  404: unknown;
};

export type GetPartiesResponses = {
  /**
   * Successful response
   */
  200: {
    /**
     * Row ID
     */
    id: string;
    /**
     * Current version ID
     */
    versionId: string;
    /**
     * Original creation ID
     */
    createdId: string;
    /**
     * Creation timestamp
     */
    createdAt: string;
    /**
     * Last update timestamp
     */
    updatedAt: string;
    /**
     * Publication timestamp
     */
    publishedAt: string;
    /**
     * Whether the row is read-only
     */
    readonly: boolean;
    data: DemoRpgDataParties;
  };
};

export type GetPartiesResponse = GetPartiesResponses[keyof GetPartiesResponses];

export type ListQuestsData = {
  /**
   * Query parameters for filtering and pagination
   */
  body: {
    /**
     * Number of items to return
     */
    first: number;
    /**
     * Cursor for pagination
     */
    after?: string;
    /**
     * Array of sorting criteria
     */
    orderBy?: Array<DemoRpgDataOrderBy>;
    /**
     * Filter conditions
     */
    where?: DemoRpgDataRowWhereInput;
  };
  path?: never;
  query?: never;
  url: '/tables/quests/rows';
};

export type ListQuestsErrors = {
  /**
   * Unauthorized - invalid or missing access token or API key
   */
  401: unknown;
};

export type ListQuestsResponses = {
  /**
   * Paginated list of rows
   */
  200: {
    edges: Array<{
      cursor: string;
      node: {
        /**
         * Row ID
         */
        id: string;
        /**
         * Current version ID
         */
        versionId: string;
        /**
         * Original creation ID
         */
        createdId: string;
        /**
         * Creation timestamp
         */
        createdAt: string;
        /**
         * Last update timestamp
         */
        updatedAt: string;
        /**
         * Publication timestamp
         */
        publishedAt: string;
        /**
         * Whether the row is read-only
         */
        readonly: boolean;
        data: DemoRpgDataQuests;
      };
    }>;
    pageInfo: {
      startCursor: string | null;
      endCursor: string | null;
      hasNextPage: boolean;
      hasPreviousPage: boolean;
    };
    totalCount: number;
  };
};

export type ListQuestsResponse = ListQuestsResponses[keyof ListQuestsResponses];

export type GetQuestsData = {
  body?: never;
  path: {
    /**
     * Row ID
     */
    rowId: string;
  };
  query?: never;
  url: '/tables/quests/row/{rowId}';
};

export type GetQuestsErrors = {
  /**
   * Unauthorized - invalid or missing access token or API key
   */
  401: unknown;
  /**
   * Not found
   */
  404: unknown;
};

export type GetQuestsResponses = {
  /**
   * Successful response
   */
  200: {
    /**
     * Row ID
     */
    id: string;
    /**
     * Current version ID
     */
    versionId: string;
    /**
     * Original creation ID
     */
    createdId: string;
    /**
     * Creation timestamp
     */
    createdAt: string;
    /**
     * Last update timestamp
     */
    updatedAt: string;
    /**
     * Publication timestamp
     */
    publishedAt: string;
    /**
     * Whether the row is read-only
     */
    readonly: boolean;
    data: DemoRpgDataQuests;
  };
};

export type GetQuestsResponse = GetQuestsResponses[keyof GetQuestsResponses];

export type ListRegionsData = {
  /**
   * Query parameters for filtering and pagination
   */
  body: {
    /**
     * Number of items to return
     */
    first: number;
    /**
     * Cursor for pagination
     */
    after?: string;
    /**
     * Array of sorting criteria
     */
    orderBy?: Array<DemoRpgDataOrderBy>;
    /**
     * Filter conditions
     */
    where?: DemoRpgDataRowWhereInput;
  };
  path?: never;
  query?: never;
  url: '/tables/regions/rows';
};

export type ListRegionsErrors = {
  /**
   * Unauthorized - invalid or missing access token or API key
   */
  401: unknown;
};

export type ListRegionsResponses = {
  /**
   * Paginated list of rows
   */
  200: {
    edges: Array<{
      cursor: string;
      node: {
        /**
         * Row ID
         */
        id: string;
        /**
         * Current version ID
         */
        versionId: string;
        /**
         * Original creation ID
         */
        createdId: string;
        /**
         * Creation timestamp
         */
        createdAt: string;
        /**
         * Last update timestamp
         */
        updatedAt: string;
        /**
         * Publication timestamp
         */
        publishedAt: string;
        /**
         * Whether the row is read-only
         */
        readonly: boolean;
        data: DemoRpgDataRegions;
      };
    }>;
    pageInfo: {
      startCursor: string | null;
      endCursor: string | null;
      hasNextPage: boolean;
      hasPreviousPage: boolean;
    };
    totalCount: number;
  };
};

export type ListRegionsResponse = ListRegionsResponses[keyof ListRegionsResponses];

export type GetRegionsData = {
  body?: never;
  path: {
    /**
     * Row ID
     */
    rowId: string;
  };
  query?: never;
  url: '/tables/regions/row/{rowId}';
};

export type GetRegionsErrors = {
  /**
   * Unauthorized - invalid or missing access token or API key
   */
  401: unknown;
  /**
   * Not found
   */
  404: unknown;
};

export type GetRegionsResponses = {
  /**
   * Successful response
   */
  200: {
    /**
     * Row ID
     */
    id: string;
    /**
     * Current version ID
     */
    versionId: string;
    /**
     * Original creation ID
     */
    createdId: string;
    /**
     * Creation timestamp
     */
    createdAt: string;
    /**
     * Last update timestamp
     */
    updatedAt: string;
    /**
     * Publication timestamp
     */
    publishedAt: string;
    /**
     * Whether the row is read-only
     */
    readonly: boolean;
    data: DemoRpgDataRegions;
  };
};

export type GetRegionsResponse = GetRegionsResponses[keyof GetRegionsResponses];

export type GetRegionsForeignKeysByLocationsData = {
  body?: never;
  path: {
    /**
     * Row ID
     */
    rowId: string;
  };
  query: {
    /**
     * Number of items to return
     */
    first: number;
    /**
     * Cursor for pagination
     */
    after?: string;
  };
  url: '/tables/regions/row/{rowId}/foreign-keys-by/locations';
};

export type GetRegionsForeignKeysByLocationsErrors = {
  /**
   * Unauthorized - invalid or missing access token or API key
   */
  401: unknown;
  /**
   * Not found
   */
  404: unknown;
};

export type GetRegionsForeignKeysByLocationsResponses = {
  /**
   * Paginated list of related rows
   */
  200: {
    edges: Array<{
      cursor: string;
      node: {
        /**
         * Row ID
         */
        id: string;
        /**
         * Current version ID
         */
        versionId: string;
        /**
         * Original creation ID
         */
        createdId: string;
        /**
         * Creation timestamp
         */
        createdAt: string;
        /**
         * Last update timestamp
         */
        updatedAt: string;
        /**
         * Publication timestamp
         */
        publishedAt: string;
        /**
         * Whether the row is read-only
         */
        readonly: boolean;
        data: DemoRpgDataLocations;
      };
    }>;
    pageInfo: {
      startCursor: string | null;
      endCursor: string | null;
      hasNextPage: boolean;
      hasPreviousPage: boolean;
    };
    totalCount: number;
  };
};

export type GetRegionsForeignKeysByLocationsResponse =
  GetRegionsForeignKeysByLocationsResponses[keyof GetRegionsForeignKeysByLocationsResponses];

export type ListStatsData = {
  /**
   * Query parameters for filtering and pagination
   */
  body: {
    /**
     * Number of items to return
     */
    first: number;
    /**
     * Cursor for pagination
     */
    after?: string;
    /**
     * Array of sorting criteria
     */
    orderBy?: Array<DemoRpgDataOrderBy>;
    /**
     * Filter conditions
     */
    where?: DemoRpgDataRowWhereInput;
  };
  path?: never;
  query?: never;
  url: '/tables/stats/rows';
};

export type ListStatsErrors = {
  /**
   * Unauthorized - invalid or missing access token or API key
   */
  401: unknown;
};

export type ListStatsResponses = {
  /**
   * Paginated list of rows
   */
  200: {
    edges: Array<{
      cursor: string;
      node: {
        /**
         * Row ID
         */
        id: string;
        /**
         * Current version ID
         */
        versionId: string;
        /**
         * Original creation ID
         */
        createdId: string;
        /**
         * Creation timestamp
         */
        createdAt: string;
        /**
         * Last update timestamp
         */
        updatedAt: string;
        /**
         * Publication timestamp
         */
        publishedAt: string;
        /**
         * Whether the row is read-only
         */
        readonly: boolean;
        data: DemoRpgDataStats;
      };
    }>;
    pageInfo: {
      startCursor: string | null;
      endCursor: string | null;
      hasNextPage: boolean;
      hasPreviousPage: boolean;
    };
    totalCount: number;
  };
};

export type ListStatsResponse = ListStatsResponses[keyof ListStatsResponses];

export type GetStatsData = {
  body?: never;
  path: {
    /**
     * Row ID
     */
    rowId: string;
  };
  query?: never;
  url: '/tables/stats/row/{rowId}';
};

export type GetStatsErrors = {
  /**
   * Unauthorized - invalid or missing access token or API key
   */
  401: unknown;
  /**
   * Not found
   */
  404: unknown;
};

export type GetStatsResponses = {
  /**
   * Successful response
   */
  200: {
    /**
     * Row ID
     */
    id: string;
    /**
     * Current version ID
     */
    versionId: string;
    /**
     * Original creation ID
     */
    createdId: string;
    /**
     * Creation timestamp
     */
    createdAt: string;
    /**
     * Last update timestamp
     */
    updatedAt: string;
    /**
     * Publication timestamp
     */
    publishedAt: string;
    /**
     * Whether the row is read-only
     */
    readonly: boolean;
    data: DemoRpgDataStats;
  };
};

export type GetStatsResponse = GetStatsResponses[keyof GetStatsResponses];

export type GetStatsForeignKeysByItemsData = {
  body?: never;
  path: {
    /**
     * Row ID
     */
    rowId: string;
  };
  query: {
    /**
     * Number of items to return
     */
    first: number;
    /**
     * Cursor for pagination
     */
    after?: string;
  };
  url: '/tables/stats/row/{rowId}/foreign-keys-by/items';
};

export type GetStatsForeignKeysByItemsErrors = {
  /**
   * Unauthorized - invalid or missing access token or API key
   */
  401: unknown;
  /**
   * Not found
   */
  404: unknown;
};

export type GetStatsForeignKeysByItemsResponses = {
  /**
   * Paginated list of related rows
   */
  200: {
    edges: Array<{
      cursor: string;
      node: {
        /**
         * Row ID
         */
        id: string;
        /**
         * Current version ID
         */
        versionId: string;
        /**
         * Original creation ID
         */
        createdId: string;
        /**
         * Creation timestamp
         */
        createdAt: string;
        /**
         * Last update timestamp
         */
        updatedAt: string;
        /**
         * Publication timestamp
         */
        publishedAt: string;
        /**
         * Whether the row is read-only
         */
        readonly: boolean;
        data: DemoRpgDataItems;
      };
    }>;
    pageInfo: {
      startCursor: string | null;
      endCursor: string | null;
      hasNextPage: boolean;
      hasPreviousPage: boolean;
    };
    totalCount: number;
  };
};

export type GetStatsForeignKeysByItemsResponse =
  GetStatsForeignKeysByItemsResponses[keyof GetStatsForeignKeysByItemsResponses];
