services:
  db:
    image: postgres:17-alpine
    ports:
      - '5437:5432'
    environment:
      POSTGRES_DB: demo_rpg_backend_test
      POSTGRES_USER: demo_rpg
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U demo_rpg -d demo_rpg_backend_test']
      interval: 5s
      timeout: 5s
      retries: 5
